/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package test.model;
import java.sql.SQLException;
import oracle.jbo.domain.Number;
import oracle.jbo.server.ApplicationModuleImpl;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---------------------------------------------------------------------

public class TestModuleImpl extends ApplicationModuleImpl implements test.model.common.TestModule  {
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public TestModuleImpl() {
  }

  /**
   * If either of the lowSal or highSal parameters are null or empty,
   * then set the MaxFetchSize on the view object to zero to avoid
   * the query's being executed.
   * 
   * @param lowSal Low Salary Value
   * @param highSal High Salary Value
   */
  public void prepareForSalaryRangeQuery(String lowSal, String highSal) {
    if (isNullOrEmpty(lowSal) || isNullOrEmpty(highSal)) {
      getEmpsInSalaryRange().setMaxFetchSize(0);
    }
    else {
      int high = Integer.parseInt(highSal);
      getEmpsInSalaryRange().setMaxFetchSize(-1);
      getEmpsInSalaryRange().setWhereClauseParam(0,number(lowSal));
      getEmpsInSalaryRange().setWhereClauseParam(1,number(highSal));
      getEmpsInSalaryRange().executeQuery();
    }
  }


  private boolean isNullOrEmpty(String s) {
    return s == null || s.equals("");
  }
  private Number number(String s) {
    try  {
      return new Number(s);      
    } catch (SQLException ex)  {
      return null;
    }
  }
  /**
   * 
   *  Sample main for debugging Business Components code using the tester.
   */
  public static void main(String[] args) {
    launchTester("test.model", "TestModuleLocal");
  }

  /**
   * 
   *  Container's getter for EmpsInSalaryRange
   */
  public EmpsInSalaryRangeImpl getEmpsInSalaryRange() {
    return (EmpsInSalaryRangeImpl)findViewObject("EmpsInSalaryRange");
  }
}
