/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package test.model;

import oracle.jbo.common.JboResourceBundle;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ContactMsgBundle extends JboResourceBundle {
  static final Object[][] sMessageStrings = 
  { { "email_LABEL", "Email Address" }, 
    { "updated_FMT_FORMAT", "dd-MMM-yyyy HH:mm:ss" }, 
    { "updated_FMT_FORMATTER", "oracle.jbo.format.DefaultDateFormatter" }, 
    { "updated_LABEL", "Last Updated" }, { "name_LABEL", "Name" } };

  /**This is the default constructor (do not remove)
   */
  public ContactMsgBundle() {
  }

  /**@return an array of key-value pairs.
   */
  public Object[][] getContents() {
    return super.getMergedArray(sMessageStrings, super.getContents());
  }
}
