/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package test.model;

import oracle.jbo.Row;
import oracle.jbo.ViewCriteriaItem;
import oracle.jbo.server.AssociationDefImpl;
import oracle.jbo.server.ViewObjectImpl;
import oracle.jbo.server.ViewRowImpl;
import oracle.jbo.server.ViewRowSetImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Sep 10 09:46:03 CEST 2009
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmpViewImpl extends fwkext.TracingViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public EmpViewImpl() {
    }

    /**
     * Returns the bind variable value for varEname.
     * @return bind variable value for varEname
     */
    public String getvarEname() {
        return (String)getNamedWhereClauseParam("varEname");
    }

    /**
     * Sets <code>value</code> for bind variable varEname.
     * @param value value to bind as varEname
     */
    public void setvarEname(String value) {
        setNamedWhereClauseParam("varEname", value);
    }


    @Override
    protected ViewRowSetImpl createViewLinkAccessorRS(AssociationDefImpl assocDef,
                                                      ViewObjectImpl accessorVO,
                                                      Row masterRow,
                                                      Object[] values) {
        ViewRowSetImpl v =  super.createViewLinkAccessorRS(assocDef, accessorVO, masterRow, 
                                           values);
        String varEname = (String)((ViewRowImpl)masterRow).getViewObject().getNamedWhereClauseParam("varEname");
        accessorVO.setNamedWhereClauseParam("varEname", varEname);
        v.setNamedWhereClauseParam("varEname", varEname);
        return v;    }
}
