/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package demo.model;

import oracle.jbo.Session;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl
{
    /**This is the default constructor (do not remove)
     */
    public AppModuleImpl() {
    }

    /**Container's getter for DeptView1
     */
    public ViewObjectImpl getDeptView_With_CSVList_of_Deptno() {
        return (ViewObjectImpl)findViewObject("DeptView_With_CSVList_of_Deptno");
    }

    /**Sample exportable method.
     */
    public void sampleAppModuleImplExportable() {
    }

    /**Sample exportable method.
     */
    public void sampleAppModuleImplExportable2(String testParam1) {
    }

    /**Sample main for debugging Business Components code using the tester.
     */
    public static void main(String[] args) {
        launchTester("demo.model", /* package name */
      "AppModuleLocal" /* Configuration Name */);
    }

    protected void prepareSession(Session session) {
        super.prepareSession(session);
        // getDBTransaction().executeCommand("alter session set sql_trace true");
    }

   /**
    * Container's getter for DeptView2.
    * @return DeptView2
    */
   public ViewObjectImpl getDeptView_With_CSVList_of_Dname()
   {
      return (ViewObjectImpl)findViewObject("DeptView_With_CSVList_of_Dname");
   }

   /**
    * Container's getter for DeptView_With_Programmatically_Set_List_Of_Dname.
    * @return DeptView_With_Programmatically_Set_List_Of_Dname
    */
   public DeptView3Impl getDeptView_With_Programmatically_Set_List_Of_Dname()
   {
      return (DeptView3Impl)findViewObject("DeptView_With_Programmatically_Set_List_Of_Dname");
   }
}
