/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package example.model;
import example.model.common.ExampleModule;

import oracle.jbo.server.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ExampleModuleImpl extends ApplicationModuleImpl implements ExampleModule {
  /**This is the default constructor (do not remove)
   */
  public ExampleModuleImpl() {
  }

  /**Sample main for debugging Business Components code using the tester.
   */
  public static void main(String[] args) {
    launchTester("example.model", /* package name */
      "ExampleModuleLocal" /* Configuration Name */);
  }
  public void exampleMethod() {
    // System.out.println("### Example Method Called ###");
  }

  /**Container's getter for EmpView
   */
  public EmpViewImpl getEmpView() {
    return (EmpViewImpl)findViewObject("EmpView");
  }
}
