/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package test.client;

import oracle.jbo.client.remote.ApplicationModuleImpl;

import test.common.AppModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Oct 06 15:03:08 CEST 2008
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleClient extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleClient() {
    }

    public void testReadOnlyScoredEmployees() {
        Object _ret =
            this.riInvokeExportedMethod(this,"testReadOnlyScoredEmployees",null,null);
        return;
    }

    public void testEntityBasedScoredEmployees() {
        Object _ret =
            this.riInvokeExportedMethod(this,"testEntityBasedScoredEmployees",null,null);
        return;
    }
}
