/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package test.client;

import java.util.List;

import oracle.jbo.client.remote.ViewUsageImpl;

import test.common.EntityBasedScoredEmployees;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Oct 06 15:09:01 CEST 2008
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EntityBasedScoredEmployeesClient extends ViewUsageImpl implements EntityBasedScoredEmployees {
    /**
     * This is the default constructor (do not remove).
     */
    public EntityBasedScoredEmployeesClient() {
    }

    public void setScoredKeysArray(List scoredKeys) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"setScoredKeysArray",new String [] {"java.util.List"},new Object[] {scoredKeys});
        return;
    }
}
