/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package test.model.client;

import oracle.jbo.client.remote.ApplicationModuleImpl;

import test.model.common.AppModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Sep 10 15:37:50 CEST 2009
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleClient extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleClient() {
    }

    public String customApplicationModuleMethodWithResult(String stringArg,
                                                          int intArg) {
        Object _ret =
            this.riInvokeExportedMethod(this,"customApplicationModuleMethodWithResult",new String [] {"java.lang.String","int"},new Object[] {stringArg, new Integer(intArg)});
        return (String)_ret;
    }


    public void customApplicationModuleMethod(String stringArg, int intArg) {
        Object _ret =
            this.riInvokeExportedMethod(this,"customApplicationModuleMethod",new String [] {"java.lang.String","int"},new Object[] {stringArg, new Integer(intArg)});
        return;
    }

    public void customApplicationModuleMethodNoArgs() {
        Object _ret =
            this.riInvokeExportedMethod(this,"customApplicationModuleMethodNoArgs",null,null);
        return;
    }

    public String customApplicationModuleMethodWithResult(String stringArg,
                                                          Integer intArg) {
        Object _ret =
            this.riInvokeExportedMethod(this,"customApplicationModuleMethodWithResult",new String [] {"java.lang.String","java.lang.Integer"},new Object[] {stringArg, intArg});
        return (String)_ret;
    }

    public void customApplicationModuleMethod(String stringArg,
                                              Integer intArg) {
        Object _ret =
            this.riInvokeExportedMethod(this,"customApplicationModuleMethod",new String [] {"java.lang.String","java.lang.Integer"},new Object[] {stringArg, intArg});
        return;
    }
}
