/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package xml2000demo;

// ---------------------------------------------------------------
// ---    File generated by Oracle Business Components for Java.
// ---------------------------------------------------------------


import oracle.jbo.server.*;
import oracle.jbo.RowIterator;
import oracle.jbo.server.ViewObjectImpl;

public class EmpViewImpl extends ViewObjectImpl {

  /**
    * This is the default constructor (do not remove)
    */
  public EmpViewImpl() {
  }

  
  /**
    * Sample exportable method added for corba test
    */
  public void sampleEmpViewImplExportable() {
  }

  
  /**
    * Sample exportable method added for corba test
    */
  public void sampleEmpViewImplExportable2(String testParam1, String testParam2) {
  }

  /**
   * 
   *  Sample exportable method.
   */
  public void sampleEmpViewImplExportable2(String testParam1) {
  }
  
}



 
