/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package toystore.model.businessobjects;

// ---------------------------------------------------------------
// ---    File generated by Oracle Business Components for Java.
// ---------------------------------------------------------------


import oracle.jbo.server.*;
import oracle.jbo.RowIterator;
import oracle.jbo.Key;
import oracle.jbo.server.util.*;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.AttributeDefImpl;
import toystore.fwk.model.businessobjects.ToyStoreEntityImpl;

public class CategoryImpl extends ToyStoreEntityImpl {
  protected static final int CATID = 0;
  protected static final int NAME = 1;
  protected static final int DESCN = 2;
  protected static final int PRODUCT = 3;


  private static EntityDefImpl mDefinitionObject;

  /**
    * This is the default constructor (do not remove)
    */
  public CategoryImpl() {
  }

  /**
   * 
   * Retrieves the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject() {
    if (mDefinitionObject == null) {
      mDefinitionObject = (EntityDefImpl)EntityDefImpl.findDefObject("toystore.model.businessobjects.Category");
    }
    return mDefinitionObject;
  }


  

  

  

  

  

  

  
  /**
    * Gets the attribute value for Catid, using the alias name Catid
    */
  public String getCatid() {
    return (String)getAttributeInternal(CATID);
  }

  
  /**
    * Sets <code>value</code> as the attribute value for Catid
    */
  public void setCatid(String value) {
    setAttributeInternal(CATID, value);
  }

  
  /**
    * Gets the attribute value for Name, using the alias name Name
    */
  public String getName() {
    return (String)getAttributeInternal(NAME);
  }

  
  /**
    * Sets <code>value</code> as the attribute value for Name
    */
  public void setName(String value) {
    setAttributeInternal(NAME, value);
  }

  
  /**
    * Gets the attribute value for Descn, using the alias name Descn
    */
  public String getDescn() {
    return (String)getAttributeInternal(DESCN);
  }

  
  /**
    * Sets <code>value</code> as the attribute value for Descn
    */
  public void setDescn(String value) {
    setAttributeInternal(DESCN, value);
  }

  

  
  /**
    * Gets the associated entity oracle.jbo.RowIterator
    */
  public RowIterator getProduct() {
    return (RowIterator)getAttributeInternal(PRODUCT);
  }
  //  Generated method. Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case CATID:
        return getCatid();
      case NAME:
        return getName();
      case DESCN:
        return getDescn();
      case PRODUCT:
        return getProduct();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }
  //  Generated method. Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
      {
      case CATID:
        setCatid((String)value);
        return;
      case NAME:
        setName((String)value);
        return;
      case DESCN:
        setDescn((String)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }

  /**
   * 
   * Creates a Key object based on given key constituents
   */
  public static Key createPrimaryKey(String catid) {
    return new Key(new Object[] {catid});
  }


  

  

  
  
}


