/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package test;

import java.util.List;
import java.util.Map;

import oracle.jbo.domain.Array;

import test.common.EntityBasedScoredEmployees;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Oct 06 15:05:35 CEST 2008
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EntityBasedScoredEmployeesImpl extends ViewObjectImplWithScoredKeyBindVariable implements EntityBasedScoredEmployees {
    /**
     * This is the default constructor (do not remove).
     */
    public EntityBasedScoredEmployeesImpl() {
    }
    public void setScoredKeysArray(List list) {
        List<Map<String,Long>> scoredKeys =(List<Map<String,Long>>)list;                                      
        setVarArrayOfStruct(newScoredKeysArray(scoredKeys));
    }

    /**
     * Returns the bind variable value for VarArrayOfStruct.
     * @return bind variable value for VarArrayOfStruct
     */
    public Array getVarArrayOfStruct() {
        return (Array)getNamedWhereClauseParam("VarArrayOfStruct");
    }

    /**
     * Sets <code>value</code> for bind variable VarArrayOfStruct.
     * @param value value to bind as VarArrayOfStruct
     */
    public void setVarArrayOfStruct(Array value) {
        setNamedWhereClauseParam("VarArrayOfStruct", value);
    }
}
