/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package test;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

import java.util.List;
import java.util.Map;

import oracle.jbo.domain.Array;

import oracle.sql.ARRAY;
import oracle.sql.ArrayDescriptor;
import oracle.sql.Datum;
import oracle.sql.STRUCT;
import oracle.sql.StructDescriptor;

import test.common.ReadOnlyScoredEmployees;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Oct 06 14:26:39 CEST 2008
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ReadOnlyScoredEmployeesImpl extends ViewObjectImplWithScoredKeyBindVariable implements ReadOnlyScoredEmployees {
    /**
     * This is the default constructor (do not remove).
     */
    public ReadOnlyScoredEmployeesImpl() {
    }

    /**
     * Returns the bind variable value for VarArrayOfStruct.
     * @return bind variable value for VarArrayOfStruct
     */
    public Array getVarArrayOfStruct() {
        return (Array)getNamedWhereClauseParam("VarArrayOfStruct");
    }
    public void setScoredKeysArray(List list) {
        List<Map<String,Long>> scoredKeys =(List<Map<String,Long>>)list;                                      
        setVarArrayOfStruct(newScoredKeysArray(scoredKeys));
    }
    /**
     * Sets <code>value</code> for bind variable VarArrayOfStruct.
     * @param value value to bind as VarArrayOfStruct
     */
    public void setVarArrayOfStruct(Array value) {
        setNamedWhereClauseParam("VarArrayOfStruct", value);
    }
}
