/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package demo.model;
import oracle.jbo.server.ViewObjectImpl;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class DeptViewImpl extends ViewObjectImpl  {
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public DeptViewImpl() {
  }

  protected void create() {
    // TODO:  Override this oracle.jbo.server.ComponentObjectImpl method
    super.create();
    addDynamicAttribute("Foo");
  }
}
