/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package test.model;

import java.util.Set;

import oracle.jbo.Key;
import oracle.jbo.Row;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;

import test.model.common.AppModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed May 07 17:57:11 CEST 2008
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }
    public void processSelectedDepartments(Set s) {
        if (s != null) {
            int numSelectedDepts = s.size();
            System.out.println("----");
            System.out.println("You selected "+numSelectedDepts+" department(s):");
            for (Object o : s) {
                Key k = (Key)o;
                Row[] foundDepts = getDepartments().findByKey(k,1);
                if (foundDepts != null && foundDepts.length == 1) {
                    Row foundDept = foundDepts[0];
                    System.out.println(foundDept.getAttribute("Deptno")+
                                       " named "+
                                       foundDept.getAttribute("Dname"));
                }
            }
            System.out.println("----");
        }        
    }

    public void processSelectedEmployees(Set s) {
        if (s != null) {
            int numSelectedEmps = s.size();
            System.out.println("----");
            System.out.println("You selected "+numSelectedEmps+" employees(s):");
            for (Object o : s) {
                Key k = (Key)o;
                Row[] foundEmps = getAllEmployees().findByKey(k,1);
                if (foundEmps != null && foundEmps.length == 1) {
                    Row foundEmp = foundEmps[0];
                    System.out.println(foundEmp.getAttribute("Empno")+
                                       " named "+
                                       foundEmp.getAttribute("Ename"));
                }
            }
        }        
    }

    /**
     * Container's getter for EmpView1.
     * @return EmpView1
     */
    public ViewObjectImpl getAllEmployees() {
        return (ViewObjectImpl)findViewObject("AllEmployees");
    }

    /**
     * Container's getter for EmployeeHierarchy.
     * @return EmployeeHierarchy
     */
    public ViewObjectImpl getEmployeeHierarchy() {
        return (ViewObjectImpl)findViewObject("EmployeeHierarchy");
    }

    /**
     * Container's getter for Departments.
     * @return Departments
     */
    public ViewObjectImpl getDepartments() {
        return (ViewObjectImpl)findViewObject("Departments");
    }
}
