/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package model.common.ejb.beanmanaged;
import javax.ejb.CreateException;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public interface AppModuleHome extends javax.ejb.EJBHome  {
  RemoteAppModule create(java.util.Hashtable clientEnv) throws CreateException, java.rmi.RemoteException;

}
