/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package oracle.srdemo.model;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;

import oracle.srdemo.model.common.AppModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl implements AppModule {
  /**This is the default constructor (do not remove)
   */
  public AppModuleImpl() {
  }
  public void setFilter(String s) {
    System.out.println("### setFilter() called s = "+s+" ###");
  }

  /**Container's getter for DeptView1
   */
  public ViewObjectImpl getDeptView1() {
    return (ViewObjectImpl)findViewObject("DeptView1");
  }

  /**Sample main for debugging Business Components code using the tester.
   */
  public static void main(String[] args) {
    launchTester("oracle.srdemo.model", /* package name */
      "AppModuleLocal" /* Configuration Name */);
  }
}
