/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
// $Header: /cvs/ADFToyStoreJSF/ToyStoreModel/src/toystore/model/dataaccess/OrdersRowImpl.java,v 1.1.1.1 2006/01/26 21:47:21 steve Exp $
package toystore.model.dataaccess;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------
// ---    File generated by Oracle Business Components for Java.
// ---------------------------------------------------------------
import oracle.jbo.server.*;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;

import toystore.model.businessobjects.OrdersImpl;
import toystore.model.datatypes.common.CreditCardNumber;
import toystore.model.datatypes.common.ExpirationDate;
public class OrdersRowImpl extends ViewRowImpl {
  public static final int ORDERID = 0;
  public static final int USERID = 1;
  public static final int SHIPADDR1 = 2;
  public static final int SHIPADDR2 = 3;
  public static final int SHIPCITY = 4;
  public static final int SHIPSTATE = 5;
  public static final int SHIPZIP = 6;
  public static final int SHIPCOUNTRY = 7;
  public static final int COURIER = 8;
  public static final int TOTALPRICE = 9;
  public static final int SHIPTOFIRSTNAME = 10;
  public static final int SHIPTOLASTNAME = 11;
  public static final int CREDITCARD = 12;
  public static final int CARDTYPE = 13;
  public static final int EXPRDATE = 14;
  public static final int EXPRMONTH = 15;
  public static final int EXPRYEAR = 16;
  public static final int BILLADDR1 = 17;
  public static final int BILLADDR2 = 18;
  public static final int BILLCITY = 19;
  public static final int BILLSTATE = 20;
  public static final int BILLZIP = 21;
  public static final int BILLCOUNTRY = 22;
  public static final int BILLTOFIRSTNAME = 23;
  public static final int BILLTOLASTNAME = 24;
  public static final int LOCALE = 25;
  public static final int ORDERDATE = 26;
  public static final int LINEITEMS = 27;
  //--[Begin Custom Code]--
  /**
   * Force the setting of the Expiration Month to set the Expiration Date
   */
  public void setExprMonth(String value) {
    setAttributeInternal(EXPRMONTH, value);
    if (getExprYear() != null) {
      setAttributeInternal(EXPRDATE,
        new ExpirationDate(getExprMonth(), getExprYear()));
    }
  }
  /**
   * Force the setting of the Expiration Year to set the Expiration Date
   */
  public void setExprYear(String value) {
    setAttributeInternal(EXPRYEAR, value);
    if (getExprMonth() != null) {
      setAttributeInternal(EXPRDATE,
        new ExpirationDate(getExprMonth(), getExprYear()));
    }
  }

  //--[End Custom Code]--
  /**
   * This is the default constructor (do not remove)
   */
  public OrdersRowImpl() {}

  /**
   * Gets Orders entity object.
   */
  public OrdersImpl getOrders() {
    return (OrdersImpl)getEntity(0);
  }
  /**
   * Gets the attribute value for ORDERID using the alias name Orderid
   */
  public DBSequence getOrderid() {
    return (DBSequence)getAttributeInternal("Orderid");
  }
  /**
   * Sets <code>value</code> as attribute value for ORDERID using the alias name Orderid
   */
  public void setOrderid(DBSequence value) {
    setAttributeInternal("Orderid", value);
  }
  /**
   * Gets the attribute value for USERID using the alias name Userid
   */
  public String getUserid() {
    return (String) getAttributeInternal("Userid");
  }
  /**
   * Sets <code>value</code> as attribute value for USERID using the alias name Userid
   */
  public void setUserid(String value) {
    //  setAttributeInternal("Userid", value);
  }
  /**
   * Gets the attribute value for SHIPADDR1 using the alias name Shipaddr1
   */
  public String getShipaddr1() {
    return (String) getAttributeInternal("Shipaddr1");
  }
  /**
   * Sets <code>value</code> as attribute value for SHIPADDR1 using the alias name Shipaddr1
   */
  public void setShipaddr1(String value) {
    setAttributeInternal("Shipaddr1", value);
  }
  /**
   * Gets the attribute value for SHIPADDR2 using the alias name Shipaddr2
   */
  public String getShipaddr2() {
    return (String) getAttributeInternal("Shipaddr2");
  }
  /**
   * Sets <code>value</code> as attribute value for SHIPADDR2 using the alias name Shipaddr2
   */
  public void setShipaddr2(String value) {
    setAttributeInternal("Shipaddr2", value);
  }
  /**
   * Gets the attribute value for SHIPCITY using the alias name Shipcity
   */
  public String getShipcity() {
    return (String) getAttributeInternal("Shipcity");
  }
  /**
   * Sets <code>value</code> as attribute value for SHIPCITY using the alias name Shipcity
   */
  public void setShipcity(String value) {
    setAttributeInternal("Shipcity", value);
  }
  /**
   * Gets the attribute value for SHIPSTATE using the alias name Shipstate
   */
  public String getShipstate() {
    return (String) getAttributeInternal("Shipstate");
  }
  /**
   * Sets <code>value</code> as attribute value for SHIPSTATE using the alias name Shipstate
   */
  public void setShipstate(String value) {
    setAttributeInternal("Shipstate", value);
  }
  /**
   * Gets the attribute value for SHIPZIP using the alias name Shipzip
   */
  public String getShipzip() {
    return (String) getAttributeInternal("Shipzip");
  }
  /**
   * Sets <code>value</code> as attribute value for SHIPZIP using the alias name Shipzip
   */
  public void setShipzip(String value) {
    setAttributeInternal("Shipzip", value);
  }
  /**
   * Gets the attribute value for SHIPCOUNTRY using the alias name Shipcountry
   */
  public String getShipcountry() {
    return (String) getAttributeInternal("Shipcountry");
  }
  /**
   * Sets <code>value</code> as attribute value for SHIPCOUNTRY using the alias name Shipcountry
   */
  public void setShipcountry(String value) {
    setAttributeInternal("Shipcountry", value);
  }
  /**
   * Gets the attribute value for COURIER using the alias name Courier
   */
  public String getCourier() {
    return (String) getAttributeInternal("Courier");
  }
  /**
   * Sets <code>value</code> as attribute value for COURIER using the alias name Courier
   */
  public void setCourier(String value) {
    setAttributeInternal("Courier", value);
  }
  /**
   * Gets the attribute value for TOTALPRICE using the alias name Totalprice
   */
  public Number getTotalprice() {
    return (Number) getAttributeInternal("Totalprice");
  }
  /**
   * Sets <code>value</code> as attribute value for TOTALPRICE using the alias name Totalprice
   */
  public void setTotalprice(Number value) {
    setAttributeInternal("Totalprice", value);
  }
  /**
   * Gets the attribute value for SHIPTOFIRSTNAME using the alias name Shiptofirstname
   */
  public String getShiptofirstname() {
    return (String) getAttributeInternal("Shiptofirstname");
  }
  /**
   * Sets <code>value</code> as attribute value for SHIPTOFIRSTNAME using the alias name Shiptofirstname
   */
  public void setShiptofirstname(String value) {
    setAttributeInternal("Shiptofirstname", value);
  }
  /**
   * Gets the attribute value for SHIPTOLASTNAME using the alias name Shiptolastname
   */
  public String getShiptolastname() {
    return (String) getAttributeInternal("Shiptolastname");
  }
  /**
   * Sets <code>value</code> as attribute value for SHIPTOLASTNAME using the alias name Shiptolastname
   */
  public void setShiptolastname(String value) {
    setAttributeInternal("Shiptolastname", value);
  }
  /**
   * Gets the attribute value for CREDITCARD using the alias name Creditcard
   */
  public CreditCardNumber getCreditcard() {
    return (CreditCardNumber)getAttributeInternal("Creditcard");
  }
  /**
   * Sets <code>value</code> as attribute value for CREDITCARD using the alias name Creditcard
   */
  public void setCreditcard(CreditCardNumber value) {
    setAttributeInternal("Creditcard", value);
  }
  /**
   * Gets the attribute value for CARDTYPE using the alias name Cardtype
   */
  public String getCardtype() {
    return (String) getAttributeInternal("Cardtype");
  }
  /**
   * Sets <code>value</code> as attribute value for CARDTYPE using the alias name Cardtype
   */
  public void setCardtype(String value) {
    setAttributeInternal("Cardtype", value);
  }
  /**
   * Gets Account entity object.
   */
  public toystore.model.businessobjects.AccountImpl getAccount() {
    return (toystore.model.businessobjects.AccountImpl) getEntity(1);
  }
  //  Generated method. Do not modify.
  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef)
    throws Exception {
    switch (index) {
    case ORDERID :
      return getOrderid();
    case USERID :
      return getUserid();
    case SHIPADDR1 :
      return getShipaddr1();
    case SHIPADDR2 :
      return getShipaddr2();
    case SHIPCITY :
      return getShipcity();
    case SHIPSTATE :
      return getShipstate();
    case SHIPZIP :
      return getShipzip();
    case SHIPCOUNTRY :
      return getShipcountry();
    case COURIER :
      return getCourier();
    case TOTALPRICE :
      return getTotalprice();
    case SHIPTOFIRSTNAME :
      return getShiptofirstname();
    case SHIPTOLASTNAME :
      return getShiptolastname();
    case CREDITCARD :
      return getCreditcard();
    case CARDTYPE :
      return getCardtype();
    case EXPRDATE :
      return getExprdate();
    case EXPRMONTH :
      return getExprMonth();
    case EXPRYEAR :
      return getExprYear();
    case BILLADDR1 :
      return getBilladdr1();
    case BILLADDR2 :
      return getBilladdr2();
    case BILLCITY :
      return getBillcity();
    case BILLSTATE :
      return getBillstate();
    case BILLZIP :
      return getBillzip();
    case BILLCOUNTRY :
      return getBillcountry();
    case BILLTOFIRSTNAME :
      return getBilltofirstname();
    case BILLTOLASTNAME :
      return getBilltolastname();
    case LOCALE :
      return getLocale();
    case ORDERDATE :
      return getOrderdate();
    case LINEITEMS :
      return getLineItems();
    default :
      return super.getAttrInvokeAccessor(index, attrDef);
    }
  }
  //  Generated method. Do not modify.
  protected void setAttrInvokeAccessor(int index, Object value,
    AttributeDefImpl attrDef) throws Exception {
    switch (index) {
    case SHIPADDR1 :
      setShipaddr1((String)value);
      return;
    case SHIPADDR2 :
      setShipaddr2((String)value);
      return;
    case SHIPCITY :
      setShipcity((String)value);
      return;
    case SHIPSTATE :
      setShipstate((String)value);
      return;
    case SHIPZIP :
      setShipzip((String)value);
      return;
    case SHIPCOUNTRY :
      setShipcountry((String)value);
      return;
    case COURIER :
      setCourier((String)value);
      return;
    case TOTALPRICE :
      setTotalprice((Number)value);
      return;
    case SHIPTOFIRSTNAME :
      setShiptofirstname((String)value);
      return;
    case SHIPTOLASTNAME :
      setShiptolastname((String)value);
      return;
    case CREDITCARD :
      setCreditcard((CreditCardNumber)value);
      return;
    case CARDTYPE :
      setCardtype((String)value);
      return;
    case EXPRDATE :
      setExprdate((ExpirationDate)value);
      return;
    case EXPRMONTH :
      setExprMonth((String)value);
      return;
    case EXPRYEAR :
      setExprYear((String)value);
      return;
    case BILLADDR1 :
      setBilladdr1((String)value);
      return;
    case BILLADDR2 :
      setBilladdr2((String)value);
      return;
    case BILLCITY :
      setBillcity((String)value);
      return;
    case BILLSTATE :
      setBillstate((String)value);
      return;
    case BILLZIP :
      setBillzip((String)value);
      return;
    case BILLCOUNTRY :
      setBillcountry((String)value);
      return;
    case BILLTOFIRSTNAME :
      setBilltofirstname((String)value);
      return;
    case BILLTOLASTNAME :
      setBilltolastname((String)value);
      return;
    case LOCALE :
      setLocale((String)value);
      return;
    case ORDERDATE :
      setOrderdate((Date)value);
      return;
    default :
      super.setAttrInvokeAccessor(index, value, attrDef);
      return;
    }
  }
  /**
   *
   * Gets the attribute value for the calculated attribute ExprMonth
   */
  public String getExprMonth() {
    return (String) getAttributeInternal(EXPRMONTH);
  }
  /**
   *
   * Gets the attribute value for the calculated attribute ExprYear
   */
  public String getExprYear() {
    return (String) getAttributeInternal(EXPRYEAR);
  }
  /**
   *
   * Gets the attribute value for EXPRDATE using the alias name Exprdate
   */
  public ExpirationDate getExprdate() {
    return (ExpirationDate)getAttributeInternal(EXPRDATE);
  }
  /**
   *
   * Sets <code>value</code> as attribute value for EXPRDATE using the alias name Exprdate
   */
  public void setExprdate(ExpirationDate value) {
    setAttributeInternal(EXPRDATE, value);
  }
  /**
   *
   *  Gets the attribute value for BILLADDR1 using the alias name Billaddr1
   */
  public String getBilladdr1() {
    return (String) getAttributeInternal(BILLADDR1);
  }
  /**
   *
   *  Sets <code>value</code> as attribute value for BILLADDR1 using the alias name Billaddr1
   */
  public void setBilladdr1(String value) {
    setAttributeInternal(BILLADDR1, value);
  }
  /**
   *
   *  Gets the attribute value for BILLADDR2 using the alias name Billaddr2
   */
  public String getBilladdr2() {
    return (String) getAttributeInternal(BILLADDR2);
  }
  /**
   *
   *  Sets <code>value</code> as attribute value for BILLADDR2 using the alias name Billaddr2
   */
  public void setBilladdr2(String value) {
    setAttributeInternal(BILLADDR2, value);
  }
  /**
   *
   *  Gets the attribute value for BILLCITY using the alias name Billcity
   */
  public String getBillcity() {
    return (String) getAttributeInternal(BILLCITY);
  }
  /**
   *
   *  Sets <code>value</code> as attribute value for BILLCITY using the alias name Billcity
   */
  public void setBillcity(String value) {
    setAttributeInternal(BILLCITY, value);
  }
  /**
   *
   *  Gets the attribute value for BILLSTATE using the alias name Billstate
   */
  public String getBillstate() {
    return (String) getAttributeInternal(BILLSTATE);
  }
  /**
   *
   *  Sets <code>value</code> as attribute value for BILLSTATE using the alias name Billstate
   */
  public void setBillstate(String value) {
    setAttributeInternal(BILLSTATE, value);
  }
  /**
   *
   *  Gets the attribute value for BILLZIP using the alias name Billzip
   */
  public String getBillzip() {
    return (String) getAttributeInternal(BILLZIP);
  }
  /**
   *
   *  Sets <code>value</code> as attribute value for BILLZIP using the alias name Billzip
   */
  public void setBillzip(String value) {
    setAttributeInternal(BILLZIP, value);
  }
  /**
   *
   *  Gets the attribute value for BILLCOUNTRY using the alias name Billcountry
   */
  public String getBillcountry() {
    return (String) getAttributeInternal(BILLCOUNTRY);
  }
  /**
   *
   *  Sets <code>value</code> as attribute value for BILLCOUNTRY using the alias name Billcountry
   */
  public void setBillcountry(String value) {
    setAttributeInternal(BILLCOUNTRY, value);
  }
  /**
   *
   *  Gets the attribute value for BILLTOFIRSTNAME using the alias name Billtofirstname
   */
  public String getBilltofirstname() {
    return (String) getAttributeInternal(BILLTOFIRSTNAME);
  }
  /**
   *
   *  Sets <code>value</code> as attribute value for BILLTOFIRSTNAME using the alias name Billtofirstname
   */
  public void setBilltofirstname(String value) {
    setAttributeInternal(BILLTOFIRSTNAME, value);
  }
  /**
   *
   *  Gets the attribute value for BILLTOLASTNAME using the alias name Billtolastname
   */
  public String getBilltolastname() {
    return (String) getAttributeInternal(BILLTOLASTNAME);
  }
  /**
   *
   *  Sets <code>value</code> as attribute value for BILLTOLASTNAME using the alias name Billtolastname
   */
  public void setBilltolastname(String value) {
    setAttributeInternal(BILLTOLASTNAME, value);
  }
  /**
   *
   *  Gets the attribute value for LOCALE using the alias name Locale
   */
  public String getLocale() {
    return (String) getAttributeInternal(LOCALE);
  }
  /**
   *
   *  Sets <code>value</code> as attribute value for LOCALE using the alias name Locale
   */
  public void setLocale(String value) {
    setAttributeInternal(LOCALE, value);
  }
  /**
   *
   *  Gets the attribute value for ORDERDATE using the alias name Orderdate
   */
  public Date getOrderdate() {
    return (Date) getAttributeInternal(ORDERDATE);
  }
  /**
   *
   *  Sets <code>value</code> as attribute value for ORDERDATE using the alias name Orderdate
   */
  public void setOrderdate(Date value) {
    setAttributeInternal(ORDERDATE, value);
  }
  /**
   *
   *  Gets the associated <code>RowIterator</code> using master-detail link LineItems
   */
  public RowIterator getLineItems() {
    return (RowIterator) getAttributeInternal(LINEITEMS);
  }
}
