/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
// $Header: /cvs/ADFToyStoreJSF/ToyStoreModel/src/toystore/model/dataaccess/ReviewOrderImpl.java,v 1.1.1.1 2006/01/26 21:47:21 steve Exp $
package toystore.model.dataaccess;
import java.sql.SQLException;
import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---------------------------------------------------------------------

public class ReviewOrderImpl extends ViewObjectImpl  {
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public ReviewOrderImpl() {
  }
 //--[Begin Custom Code]--
  public void setOrderToFind(String id) {
    try {
      if (id != null) {
        Number orderId = new Number(id);
        setWhereClauseParam(0,orderId);
        return;
      }
    }
    catch (SQLException sqlEx) {
    }
    setWhereClauseParam(0,null);
  }
 //--[End Custom Code]--
}
