/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package sample.client;

import oracle.jbo.client.remote.ApplicationModuleImpl;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;

import sample.common.TestModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TestModuleClient extends ApplicationModuleImpl implements TestModule {
    /**This is the default constructor (do not remove)
     */
    public TestModuleClient() {
    }

    public void createNewEmployee(String Ename, String Job, Number Mgr, 
                                  Date Hiredate, Number Sal, Number Comm, 
                                  Number Deptno) {
        Object _ret = 
            this.riInvokeExportedMethod(this,"createNewEmployee",new String [] {"java.lang.String","java.lang.String","oracle.jbo.domain.Number","oracle.jbo.domain.Date","oracle.jbo.domain.Number","oracle.jbo.domain.Number","oracle.jbo.domain.Number"},new Object[] {Ename, Job, Mgr, Hiredate, Sal, Comm, Deptno});
        return;
    }
}
