/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package test.model;

import oracle.jbo.Row;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;

import test.model.common.MailService;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Nov 03 19:52:03 CET 2009
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MailServiceImpl extends ApplicationModuleImpl implements MailService {
    /**
     * This is the default constructor (do not remove).
     */
    public MailServiceImpl() {
    }

    public void createNewMailAndPrimaryRecipient() {
        Row msg = getEmailMessage().createRow();
        getEmailMessage().insertRow(msg);
        Row recip = getEmailRecipients().createRow();
        getEmailRecipients().insertRow(recip);
        // recip.setNewRowState(Row.STATUS_INITIALIZED);
        // msg.setNewRowState(Row.STATUS_INITIALIZED);
        
    }
    /**
     * Container's getter for EmailMessage.
     * @return EmailMessage
     */
    public ViewObjectImpl getEmailMessage() {
        return (ViewObjectImpl)findViewObject("EmailMessage");
    }

    /**
     * Container's getter for EmailRecipients.
     * @return EmailRecipients
     */
    public ViewObjectImpl getEmailRecipients() {
        return (ViewObjectImpl)findViewObject("EmailRecipients");
    }

    /**
     * Container's getter for EmailMessageFkLink1.
     * @return EmailMessageFkLink1
     */
    public ViewLinkImpl getEmailMessageFkLink1() {
        return (ViewLinkImpl)findViewLink("EmailMessageFkLink1");
    }
}
