/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package bug.model;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl {
    /**This is the default constructor (do not remove)
     */
    public AppModuleImpl() {
    }

    /**Container's getter for EmployeesView1
     */
    public EmployeesViewImpl getEmployeesView1() {
        return (EmployeesViewImpl)findViewObject("EmployeesView1");
    }

    /**Container's getter for EmployeesView2
     */
    public EmployeesViewImpl getEmployeesView2() {
        return (EmployeesViewImpl)findViewObject("EmployeesView2");
    }

    /**Container's getter for EmpManagerFkLink1
     */
    public ViewLinkImpl getEmpManagerFkLink1() {
        return (ViewLinkImpl)findViewLink("EmpManagerFkLink1");
    }

    /**Sample main for debugging Business Components code using the tester.
     */
    public static void main(String[] args) {
        launchTester("bug.model", /* package name */
      "AppModuleLocal" /* Configuration Name */);
    }
}
