package test.common;
import oracle.jbo.ViewObject;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------
/**
 * 
 * Generated interface. Do not modify.
 */

public interface EmpView extends ViewObject {
  void setNamesToFind(String[] names);
}