/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package davelaar.demo.model.queries;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Oct 02 04:22:02 CEST 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmployeesViewImpl
  extends ViewObjectImpl
{
  /**
   * This is the default constructor (do not remove).
   */
  public EmployeesViewImpl()
  {
  }

  /**
   * Returns the variable value for BEmployeeId.
   * @return variable value for BEmployeeId
   */
  public String getBEmployeeId()
  {
    return (String) ensureVariableManager().getVariableValue("BEmployeeId");
  }

  /**
   * Sets <code>value</code> for variable BEmployeeId.
   * @param value value to bind as BEmployeeId
   */
  public void setBEmployeeId(String value)
  {
    ensureVariableManager().setVariableValue("BEmployeeId", value);
  }

  /**
   * Returns the variable value for BLastName.
   * @return variable value for BLastName
   */
  public String getBLastName()
  {
    return (String) ensureVariableManager().getVariableValue("BLastName");
  }

  /**
   * Sets <code>value</code> for variable BLastName.
   * @param value value to bind as BLastName
   */
  public void setBLastName(String value)
  {
    ensureVariableManager().setVariableValue("BLastName", value);
  }
}
