/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package test.model.common;
import oracle.jbo.common.JboResourceBundle;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public class UploadedFilesImplMsgBundle extends JboResourceBundle {

    static final Object[][] sMessageStrings = 
    {
{ "Filename_LABEL", "File Name" },
{ "DateCreated_LABEL", "Date Created" },
{ "DateCreated_FMT_FORMATTER", "oracle.jbo.format.DefaultDateFormatter" },
{ "DateCreated_FMT_FORMAT", "dd-MMM-yyyy HH:mm:ss" }};

    /**This is the default constructor (do not remove)
     */
    public UploadedFilesImplMsgBundle() {
  }

  /**@return an array of key-value pairs.
   */
  public Object[][] getContents() {
    return super.getMergedArray(sMessageStrings, super.getContents());
  }
}
