/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package oracle.demo.model.common;

import java.util.List;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jul 11 14:46:12 BST 2012
// ---------------------------------------------------------------------
public interface AutoReduceAM extends ApplicationModule {
    List<String> autoSuggestCandidates(String searchTerm, int returnCount);
}
