/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package test.model;

import oracle.jbo.Session;
import oracle.jbo.server.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TestModuleImpl extends ApplicationModuleImpl {
  /**This is the default constructor (do not remove)
   */
  public TestModuleImpl() {
  }

  /**Sample main for debugging Business Components code using the tester.
   */
  public static void main(String[] args) {
    launchTester("test.model", /* package name */
      "TestModuleLocal" /* Configuration Name */);
  }

  /**Container's getter for EditDepartment
   */
  public DeptViewImpl getEditDepartment() {
    return (DeptViewImpl)findViewObject("EditDepartment");
  }

  /**Container's getter for DepartmentList
   */
  public DeptViewImpl getDepartmentList() {
    return (DeptViewImpl)findViewObject("DepartmentList");
  }
  protected void prepareSession(Session session) {
    super.prepareSession(session);
    getEditDepartment().setMaxFetchSize(1);
  }
}
