/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package example.model.client;
import example.model.common.ExampleModule;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ExampleModuleClient extends ApplicationModuleImpl implements ExampleModule {
  /**This is the default constructor (do not remove)
   */
  public ExampleModuleClient() {
  }
  public void exampleMethod() {
    Object _ret = this.riInvokeExportedMethod(this,"exampleMethod",null,null);
    return;
  }
}
