/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package toystore.model.dataaccess.common;
import oracle.jbo.common.JboResourceBundle;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public class FindProductsRowImplMsgBundle extends JboResourceBundle {
  static final Object[][] sMessageStrings = {
{ "ProductName_LABEL", "Product Name" }};

  /**This is the default constructor (do not remove)
   */
  public FindProductsRowImplMsgBundle() {
  }

  /**@return an array of key-value pairs.
   */
  public Object[][] getContents() {
    return super.getMergedArray(sMessageStrings, super.getContents());
  }
}
