/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
// $Header: /cvs/ADFToyStoreJSF/ToyStoreModel/src/toystore/model/dataaccess/common/ItemsForSaleRowImplMsgBundle.java,v 1.1.1.1 2006/01/26 21:47:22 steve Exp $
package toystore.model.dataaccess.common;
import oracle.jbo.common.JboResourceBundle;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---------------------------------------------------------------------
public class ItemsForSaleRowImplMsgBundle extends JboResourceBundle {
  static final Object[][] sMessageStrings =
  {
{ "InStock_LABEL", "In Stock" },
{ "Name_LABEL", "Item Name" },
{ "Listprice_LABEL", "Unit Price" },
{ "Itemid_LABEL", "Item ID" }};

  /**
   *
   *  This is the default constructor (do not remove)
   */
  public ItemsForSaleRowImplMsgBundle() {
  }

  /**
   *
   * @return an array of key-value pairs.
   */
  public Object[][] getContents() {
    return super.getMergedArray(sMessageStrings, super.getContents());
  }
}
