/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
// $Header: /cvs/ADFToyStoreJSF/ToyStoreModel/src/toystore/model/dataaccess/common/ShoppingCartRowImplMsgBundle.java,v 1.1.1.1 2006/01/26 21:47:22 steve Exp $
package toystore.model.dataaccess.common;
import oracle.jbo.common.JboResourceBundle;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------
public class ShoppingCartRowImplMsgBundle extends JboResourceBundle {
  static final Object[][] sMessageStrings = {
    { "Listprice_FMT_FORMAT", "$0.00" },
    { "ExtendedTotal_FMT_FORMATTER", "oracle.jbo.format.DefaultNumberFormatter" },
    { "InStock_LABEL", "Availability" },
    { "Name_LABEL", "Item Name" },
    { "Listprice_LABEL", "Unit Price" },
    { "Description_LABEL", "Description" },
    { "Listprice_FMT_FORMATTER", "oracle.jbo.format.DefaultNumberFormatter" },
    { "ExtendedTotal_LABEL", "Total" },
    { "ExtendedTotal_FMT_FORMAT", "$0.00" },
    { "Quantity_LABEL", "Quantity" },
    { "Itemid_LABEL", "Item ID" }
  };

  /**
   *
   * This is the default constructor (do not remove)
   */
  public ShoppingCartRowImplMsgBundle() {
  }

  /**
   *
   * @return an array of key-value pairs.
   */
  public Object[][] getContents() {
    return super.getMergedArray(sMessageStrings, super.getContents());
  }
}
