/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package test.model.client;

import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.client.remote.ApplicationModuleImpl;

import test.model.common.AppModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jan 20 12:31:33 CET 2009
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleClient extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleClient() {
    }

    public void moveSelectedEmployeeNodeDownInRowIterator(RowIterator ri,
                                                          Key selectedEmpKey) {
        Object _ret =
            this.riInvokeExportedMethod(this,"moveSelectedEmployeeNodeDownInRowIterator",new String [] {"oracle.jbo.RowIterator","oracle.jbo.Key"},new Object[] {ri, selectedEmpKey});
        return;
    }

    public void moveSelectedEmployeeNodeUpInRowIterator(RowIterator ri,
                                                        Key selectedEmpKey) {
        Object _ret =
            this.riInvokeExportedMethod(this,"moveSelectedEmployeeNodeUpInRowIterator",new String [] {"oracle.jbo.RowIterator","oracle.jbo.Key"},new Object[] {ri, selectedEmpKey});
        return;
    }
}
