/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package test.example;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---------------------------------------------------------------------

public class MenImpl extends PeopleImpl {
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public MenImpl() {
  }

    /**Sample exportable method.
     */
    public void sampleMenImplExportable() {
    }

    /**Sample exportable method.
     */
    public void sampleMenImplExportable2(String testParam1) {
    }
}
