/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package test.example;

import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---------------------------------------------------------------------

public class MenRowImpl extends PeopleRowImpl implements test.example.common.MenRow  {


    public static final int MAXATTRCONST = oracle.jbo.server.ViewDefImpl.getMaxAttrConst("test.example.People");
    public static final int MANATTR = MAXATTRCONST;

    /**
     * 
     *  This is the default constructor (do not remove)
     */
  public MenRowImpl() {
  }

  //  Generated method. Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if (index == MANATTR) {
            return getManAttr();
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }
  //  Generated method. Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if (index == MANATTR) {
            setManAttr((String)value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
    }

  /**
   * 
   *  Gets Person entity object.
   */
  public PersonImpl getPerson() {
    return (ManImpl)getEntity(0);
  }

  /**
   * 
   *  Gets the attribute value for ID using the alias name Id
   */
  public Number getId() {
    return super.getId();
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for ID using the alias name Id
   */
  public void setId(Number value) {
    super.setId(value);
  }

  /**
   * 
   *  Gets the attribute value for SEX using the alias name Sex
   */
  public String getSex() {
    return super.getSex();
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for SEX using the alias name Sex
   */
  public void setSex(String value) {
    super.setSex(value);
  }

  /**
   * 
   *  Gets the attribute value for NAME using the alias name Name
   */
  public String getName() {
    return super.getName();
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for NAME using the alias name Name
   */
  public void setName(String value) {
    super.setName(value);
  }

  /**
   * 
   *  Gets the attribute value for MAN_ATTR using the alias name ManAttr
   */
  public String getManAttr() {
    return (String)getAttributeInternal(MANATTR);
  }

  /**
   * 
   *  Sets <code>value</code> as attribute value for MAN_ATTR using the alias name ManAttr
   */
  public void setManAttr(String value) {
    setAttributeInternal(MANATTR, value);
  }
  public void doPersonThing() {
   System.out.println("MenRowImpl: doPersonThing");
   ((ManImpl)getPerson()).doPersonThing();
  }

    /**Sample exportable method.
     */
    public void sampleMenRowImplExportable() {
    }

    /**Sample exportable method.
     */
    public void sampleMenRowImplExportable2(String testParam1) {
    }
}
