/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package test.model;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ListBasedOnTableFunctionImpl extends ViewObjectImpl {
  /**This is the default constructor (do not remove)
   */
  public ListBasedOnTableFunctionImpl() {
  }

  /**Gets the bind variable value for Bind_ListType
   */
  public String getBind_ListType() {
    return (String)getNamedWhereClauseParam("Bind_ListType");
  }

  /**Sets <code>value</code> for bind variable Bind_ListType
   */
  public void setBind_ListType(String value) {
    setNamedWhereClauseParam("Bind_ListType", value);
  }
}
