/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package test.model;

import oracle.jbo.Key;
import oracle.jbo.Row;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;

import test.model.common.AppModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Nov 24 12:25:30 CET 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }

    public void performAppModuleLevelWork(Integer deptno, String locValue) {
        Row[] found = getDeptView1().findByKey(new Key(new Object[]{deptno}), 1);
        if (found != null && found.length == 1) {
            found[0].setAttribute("Loc",locValue);
            getDBTransaction().commit();
        }
    }
    /**
     * Container's getter for DeptView1.
     * @return DeptView1
     */
    public ViewObjectImpl getDeptView1() {
        return (ViewObjectImpl)findViewObject("DeptView1");
    }
}
