/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package test.model;
import java.sql.SQLException;
import oracle.jbo.Key;
import oracle.jbo.Row;
import oracle.jbo.ViewObject;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.domain.Number;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---------------------------------------------------------------------

public class TestModuleImpl extends ApplicationModuleImpl implements test.model.common.TestModule  {
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public TestModuleImpl() {
  }

  public void deleteMultipleEmpsByEmpno(String[] empnos) {
    if (empnos != null) {
      ViewObject voEmps = getEmpView();
      for (int z = 0, numEmps = empnos.length; z < numEmps; z++) {
        Number curEmpno = null;
        try { curEmpno = new Number(empnos[z]); }
        catch (SQLException s) {/* skip if not a valid number */ }
        Key k = new Key(new Object[]{curEmpno});
        Row[] empToDelete = voEmps.findByKey(k,1);
        if (empToDelete.length > 0) {
          empToDelete[0].remove();
        }      
      }
      getTransaction().commit();
    }
  }
  /**
   * 
   *  Sample main for debugging Business Components code using the tester.
   */
  public static void main(String[] args) {
    launchTester("test.model", "TestModuleLocal");
  }

  /**
   * 
   *  Container's getter for EmpView
   */
  public EmpViewImpl getEmpView() {
    return (EmpViewImpl)findViewObject("EmpView");
  }


}
