/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package toystore.view.pageDefs;
import oracle.jbo.common.JboResourceBundle;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class confirmshippinginfoPageDefMsgBundle extends JboResourceBundle {
  static final Object[][] sMessageStrings =
  {
{ "ExprYear_null", "YYYY" },
{ "Courier_null", "<Select>" },
{ "Cardtype_null", "<Select>" }};

  /**This is the default constructor (do not remove)
   */
  public confirmshippinginfoPageDefMsgBundle() {
  }

  /**@return an array of key-value pairs.
   */
  public Object[][] getContents() {
    return super.getMergedArray(sMessageStrings, super.getContents());
  }
}
