/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package toystore.view.pageDefs;

import oracle.jbo.common.JboResourceBundle;

// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class signinPageDefMsgBundle extends JboResourceBundle {

  static final Object[][] sMessageStrings =
  {
{ "validSignon_username_var_LABEL", "Username" },
{ "validSignon_password_var_TOOLTIP", "Enter your password" },
{ "validSignon_username_var_TOOLTIP", "Enter your username" },
{ "validSignon_password_var_LABEL", "Password" }};

  /**This is the default constructor (do not remove)
   */
  public signinPageDefMsgBundle() {
  }

  /**@return an array of key-value pairs.
   */
  public Object[][] getContents() {
    return super.getMergedArray(sMessageStrings, super.getContents());
  }
}
