/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package test.model;
import oracle.jbo.server.ViewObjectImpl;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---------------------------------------------------------------------

public class DynamicViewObjectImpl extends ViewObjectImpl  {
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public DynamicViewObjectImpl() {
  }

  /**
   * 
   *  Sample exportable method.
   */
  public void sampleViewObjImplExportable() {
  }

  /**
   * 
   *  Sample exportable method.
   */
  public void sampleViewObjImplExportable2(String testParam1) {
  }

  /**
   * 
   *  Sample exportable method.
   */
  public void sampleDynamicViewObjectImplExportable() {
  }

  /**
   * 
   *  Sample exportable method.
   */
  public void sampleDynamicViewObjectImplExportable2(String testParam1) {
  }
}
