/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package test.model.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Apr 01 14:16:16 CEST 2009
// ---------------------------------------------------------------------
public interface DeptView extends ViewObject {
    long getLastRequery();
}
