/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package demo.model.businessobjects;
import oracle.jbo.ApplicationModule;
import oracle.jbo.ViewObject;
import oracle.jbo.server.DBTransaction;
import oracle.jbo.server.EntityDefImpl;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class DeptDefImpl extends EntityDefImpl  {
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public DeptDefImpl() {
  }
  private static final String LOOKUPVO_INSTNAME = "LookupDeptnoByDname";
  private static final String LOOKUPVO_DEFNAME = "demo.model.dataaccess.LookupDeptnoByDname";
  /**
   * Lookup the Deptno based on the Dname using a "utility" view object
   * 
   * NOTE: The entity def class is a shared class, so we take in the
   * ====  current DBTransaction so that it can operate in a threadsafe
   *       way using each current users transaction and related root
   *       application module instance.
   *       
   *       If the Deptno lookup needs to also consider Deptno's that might be
   *       new in the cache in the current transaction, we might consider 
   *       walking the Dept entity cache first using the 
   *       getAllEntityInstancesIterator() method.
   *       
   * @return Number
   * @param value
   */
  public DeptImpl lookupDeptByDname(String value, DBTransaction txn) {
    ApplicationModule am = txn.getRootApplicationModule();
    /*
     * See if the Utility VO instance is already there and use it if so.
     * If not, create it the first time. Does not need to be synchronized
     * since we're doing this in the context of the DBTransaction passed in.
     */
    ViewObject v = am.findViewObject(LOOKUPVO_INSTNAME);
    if (v == null) {
      v = am.createViewObject(LOOKUPVO_INSTNAME,LOOKUPVO_DEFNAME);
    }
    v.setWhereClauseParam(0,value);
    v.executeQuery();
    if (v.first() == null) {
      return null;
    }
    else {
      return (DeptImpl)findByPrimaryKey(txn,createKey(v.first()));
    }
  }  
}
