PROMPT Building demonstration tables.  Please wait.
drop sequence emp_rank_table_seq;
drop sequence dept_rank_table_seq;
create sequence emp_rank_table_seq start with 1000;
create sequence dept_rank_table_seq start with 41;

DROP TABLE EMP_WITH_RANK;
DROP TABLE DEPT_RANK;


CREATE TABLE DEPT_RANK (
 DEPTNO NUMBER(2),
 DNAME VARCHAR2(14),
 LOC VARCHAR2(13),
 CONSTRAINT DEPT_RANK_PK PRIMARY KEY (DEPTNO))
 ROWDEPENDENCIES
 ;

INSERT INTO DEPT_RANK VALUES (10, 'ACCOUNTING', 'NEW YORK');
INSERT INTO DEPT_RANK VALUES (20, 'RESEARCH',   'DALLAS');
INSERT INTO DEPT_RANK VALUES (30, 'SALES',      'CHICAGO');
INSERT INTO DEPT_RANK VALUES (40, 'OPERATIONS', 'BOSTON');

CREATE TABLE EMP_WITH_RANK (
 EMPNO NUMBER(4) NOT NULL,
 ENAME VARCHAR2(10),
 JOB VARCHAR2(9),
 MGR NUMBER(4),
 HIREDATE DATE,
 SAL NUMBER(7, 2),
 COMM NUMBER(7, 2),
 DEPTNO NUMBER(2), 
 EMP_RANK NUMBER(5),
 CONSTRAINT EMPLOYEE_RANK_PK PRIMARY KEY (EMPNO),
 CONSTRAINT WORKS_IN_DEPT_RANK FOREIGN KEY (DEPTNO) REFERENCES DEPT_RANK ON DELETE SET NULL)
 ROWDEPENDENCIES 
 ;

INSERT INTO EMP_WITH_RANK(EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO) VALUES
        (7369, 'SMITH',  'CLERK',     7902,
        TO_DATE('17-DEC-1980', 'DD-MON-YYYY'),  800, NULL, 20);
INSERT INTO EMP_WITH_RANK(EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO) VALUES
        (7499, 'ALLEN',  'SALESMAN',  7698,
        TO_DATE('20-FEB-1981', 'DD-MON-YYYY'), 1600,  300, 30);
INSERT INTO EMP_WITH_RANK(EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO) VALUES
        (7521, 'WARD',   'SALESMAN',  7698,
        TO_DATE('22-FEB-1981', 'DD-MON-YYYY'), 1250,  500, 30);
INSERT INTO EMP_WITH_RANK(EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO) VALUES
        (7566, 'JONES',  'MANAGER',   7839,
        TO_DATE('2-APR-1981', 'DD-MON-YYYY'),  2975, NULL, 20);
INSERT INTO EMP_WITH_RANK(EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO) VALUES
        (7654, 'MARTIN', 'SALESMAN',  7698,
        TO_DATE('28-SEP-1981', 'DD-MON-YYYY'), 1250, 1400, 30);
INSERT INTO EMP_WITH_RANK(EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO) VALUES
        (7698, 'BLAKE',  'MANAGER',   7839,
        TO_DATE('1-MAY-1981', 'DD-MON-YYYY'),  2850, NULL, 30);
INSERT INTO EMP_WITH_RANK(EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO) VALUES
        (7782, 'CLARK',  'MANAGER',   7839,
        TO_DATE('9-JUN-1981', 'DD-MON-YYYY'),  2450, NULL, 10);
INSERT INTO EMP_WITH_RANK(EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO) VALUES
        (7788, 'SCOTT',  'ANALYST',   7566,
        TO_DATE('09-DEC-1982', 'DD-MON-YYYY'), 3000, NULL, 20);
INSERT INTO EMP_WITH_RANK(EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO) VALUES
        (7839, 'KING',   'PRESIDENT', NULL,
        TO_DATE('17-NOV-1981', 'DD-MON-YYYY'), 5000, NULL, 10);
INSERT INTO EMP_WITH_RANK(EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO) VALUES
        (7844, 'TURNER', 'SALESMAN',  7698,
        TO_DATE('8-SEP-1981', 'DD-MON-YYYY'),  1500,    0, 30);
INSERT INTO EMP_WITH_RANK(EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO) VALUES
        (7876, 'ADAMS',  'CLERK',     7788,
        TO_DATE('12-JAN-1983', 'DD-MON-YYYY'), 1100, NULL, 20);
INSERT INTO EMP_WITH_RANK(EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO) VALUES
        (7900, 'JAMES',  'CLERK',     7698,
        TO_DATE('3-DEC-1981', 'DD-MON-YYYY'),   950, NULL, 30);
INSERT INTO EMP_WITH_RANK(EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO) VALUES
        (7902, 'FORD',   'ANALYST',   7566,
        TO_DATE('3-DEC-1981', 'DD-MON-YYYY'),  3000, NULL, 20);
INSERT INTO EMP_WITH_RANK(EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO) VALUES
        (7934, 'MILLER', 'CLERK',     7782,
        TO_DATE('23-JAN-1982', 'DD-MON-YYYY'), 1300, NULL, 10);

DECLARE
  lv_rank INTEGER;
BEGIN
  FOR J IN (SELECT DEPTNO FROM DEPT_RANK ORDER BY DEPTNO) LOOP
    lv_rank := 0;
    FOR I IN (SELECT EMPNO FROM EMP_WITH_RANK WHERE DEPTNO = j.deptno ORDER BY (NVL(SAL,0)+NVL(COMM,0)) DESC) LOOP
      lv_rank := lv_rank + 1;
      UPDATE EMP_WITH_RANK SET EMP_RANK = lv_rank WHERE EMPNO = i.empno;
    END LOOP;
  END LOOP;
END;
.
/
COMMIT;

REM ALTER TABLE EMP_WITH_RANK ADD (
REM        CONSTRAINT MANAGED_BY FOREIGN KEY (MGR) 
REM                  REFERENCES EMP_WITH_RANK);

CREATE INDEX DEPTNO_ON_EMP_WITH_RANK ON EMP_WITH_RANK(DEPTNO);

create or replace trigger dept_rank_table_befins
before insert on dept_rank for each row
begin
  if (:new.deptno is null or :new.deptno < 0) then
    select dept_rank_table_seq.nextval into :new.deptno from dual;
  end if;
end;
.
/
create or replace trigger emp_rank_table_befins
before insert on emp_with_rank for each row
begin
  if (:new.empno is null or :new.empno < 0) then
    select emp_rank_Table_seq.nextval into :new.empno from dual;
  end if;
end;
.
/

PROMPT Demonstration table build is complete.


PURGE RECYCLEBIN
/

