/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package demo.model.client;
import demo.model.common.TestModule;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TestModuleClient extends ApplicationModuleImpl implements TestModule {
  /**This is the default constructor (do not remove)
   */
  public TestModuleClient() {
  }
  public void doSomething() {
    Object _ret = this.riInvokeExportedMethod(this,"doSomething",null,null);
    return;
  }
}
