drop table dept_with_boolean;
CREATE TABLE DEPT_with_boolean (
 DEPTNO NUMBER(2),
 DNAME VARCHAR2(14),
 LOC VARCHAR2(13),
 SELECTED VARCHAR2(5) DEFAULT 'F',
 CONSTRAINT DEPT_WITH_BOOLEAN_PK PRIMARY KEY (DEPTNO))
 ;

INSERT INTO DEPT_with_boolean(DEPTNO,DNAME,LOC) VALUES (10, 'ACCOUNTING', 'NEW YORK');
INSERT INTO DEPT_with_boolean(DEPTNO,DNAME,LOC) VALUES (20, 'RESEARCH',   'DALLAS');
INSERT INTO DEPT_with_boolean(DEPTNO,DNAME,LOC) VALUES (30, 'SALES',      'CHICAGO');
INSERT INTO DEPT_with_boolean(DEPTNO,DNAME,LOC) VALUES (40, 'OPERATIONS', 'BOSTON');

Commit;
