/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package davelaar.demo.model.service.client;

import davelaar.demo.model.service.common.HRService;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jun 10 15:35:22 CEST 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HRServiceClient
  extends ApplicationModuleImpl
  implements HRService
{
  /**
   * This is the default constructor (do not remove).
   */
  public HRServiceClient()
  {
  }

  public void queryByKeyValue(String viewObjectUsage, oracle.jbo.domain.Number keyValue)
  {
    Object _ret = this.riInvokeExportedMethod(this,"queryByKeyValue",new String [] {"java.lang.String","oracle.jbo.domain.Number"},new Object[] {viewObjectUsage, keyValue});
    return;
  }

  public void employeeQuickSearch(String searchString)
  {
    Object _ret = this.riInvokeExportedMethod(this,"employeeQuickSearch",new String [] {"java.lang.String"},new Object[] {searchString});
    return;
  }

  public void queryByKeyValue(String viewObjectUsage, String keyValue)
  {
    Object _ret = this.riInvokeExportedMethod(this,"queryByKeyValue",new String [] {"java.lang.String","java.lang.String"},new Object[] {viewObjectUsage, keyValue});
    return;
  }
}
