/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package test.model.client;
import oracle.jbo.client.remote.RowImpl;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---------------------------------------------------------------------

public class EmployeeListRowClient extends RowImpl  {
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public EmployeeListRowClient() {
  }

  public oracle.jbo.domain.Number getEmpno() {
    return (oracle.jbo.domain.Number)getAttribute("Empno");
  }

  public void setEmpno(oracle.jbo.domain.Number param0) {
    setAttribute("Empno", param0);
  }

  public String getEname() {
    return (String)getAttribute("Ename");
  }

  public void setEname(String param0) {
    setAttribute("Ename", param0);
  }

  public Boolean getSelected() {
    return (Boolean)getAttribute("Selected");
  }

  public void setSelected(Boolean param0) {
    setAttribute("Selected", param0);
  }
}
