/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package test.model.client;
import oracle.jbo.client.remote.ViewUsageImpl;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---------------------------------------------------------------------

public class EmployeeListClient extends ViewUsageImpl implements test.model.common.EmployeeList  {
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public EmployeeListClient() {
  }

  public test.model.common.EmployeeListRow findEmployeeListRowByKey(oracle.jbo.domain.Number empno) {
    Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "findEmployeeListRowByKey", new String[] {"oracle.jbo.domain.Number"}, new Object[] {empno});
    return (test.model.common.EmployeeListRow)_ret;
  }

  public void markEmployeeAsSelected(oracle.jbo.domain.Number empno) {
    Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "markEmployeeAsSelected", new String[] {"oracle.jbo.domain.Number"}, new Object[] {empno});
    return;
  }

  public void markEmployeeAsSelectedUsingString(String empnoString) {
    Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "markEmployeeAsSelectedUsingString", new String[] {"java.lang.String"}, new Object[] {empnoString});
    return;
  }

  public void resetSelection() {
    Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "resetSelection", null, null);
    return;
  }










}
