/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package test.model.client;
import oracle.jbo.client.remote.ApplicationModuleImpl;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---------------------------------------------------------------------

public class TestModuleClient extends ApplicationModuleImpl implements test.model.common.TestModule  {
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public TestModuleClient() {
  }

  public oracle.jbo.Row[] getSelectedEmployees() {
    Object _ret = this.riInvokeExportedMethod(this, "getSelectedEmployees", null, null);
    return (oracle.jbo.Row[])_ret;
  }

  public void markEmpnosSelected(String[] empnos) {
    Object _ret = this.riInvokeExportedMethod(this, "markEmpnosSelected", new String[] {"[Ljava.lang.String;"}, new Object[] {empnos});
    return;
  }

  public void resetSelection() {
    Object _ret = this.riInvokeExportedMethod(this, "resetSelection", null, null);
    return;
  }




}
