/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package test.model.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Oct 13 17:47:00 CEST 2008
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    void setUserMapValue(String key, String value);
}
