/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package oracle.fod.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface EmpView extends ViewObject {
    void setNamesToFind(String[] names);
}
