/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package demo.client;
import demo.common.DeptView;

import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DeptViewClient extends ViewUsageImpl implements DeptView {
  /**This is the default constructor (do not remove)
   */
  public DeptViewClient() {
  }
  public void testConsistencyOfCurrentRow() {
    Object _ret = 
      getApplicationModuleProxy().riInvokeExportedMethod(this,"testConsistencyOfCurrentRow",null,null);
    return;
  }
}
