package demo.model.queries;
import demo.model.entities.EmployeeImpl;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmployeesListRowImpl extends ViewRowImpl {
  public static final int VALUE = 0;
  public static final int LABEL = 1;
  public static final int FILTER = 2;
  public static final int FIRSTNAME = 3;
  public static final int LASTNAME = 4;

  /**This is the default constructor (do not remove)
   */
  public EmployeesListRowImpl() {
  }

  /**Gets Employee entity object.
   */
  public EmployeeImpl getEmployee() {
    return (EmployeeImpl)getEntity(0);
  }

  /**Gets the attribute value for EMPLOYEE_ID using the alias name Value
   */
  public Number getValue() {
    return (Number) getAttributeInternal(VALUE);
  }

  /**Sets <code>value</code> as attribute value for EMPLOYEE_ID using the alias name Value
   */
  public void setValue(Number value) {
    setAttributeInternal(VALUE, value);
  }

  /**Gets the attribute value for the calculated attribute Label
   */
  public String getLabel() {
    return getFirstName()+" "+getLastName();
    // return (String) getAttributeInternal(LABEL);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute Label
   */
  public void setLabel(String value) {
    setAttributeInternal(LABEL, value);
  }

  /**Gets the attribute value for DEPARTMENT_ID using the alias name Filter
   */
  public Number getFilter() {
    return (Number) getAttributeInternal(FILTER);
  }

  /**Sets <code>value</code> as attribute value for DEPARTMENT_ID using the alias name Filter
   */
  public void setFilter(Number value) {
    setAttributeInternal(FILTER, value);
  }

  /**Gets the attribute value for FIRST_NAME using the alias name FirstName
   */
  public String getFirstName() {
    return (String) getAttributeInternal(FIRSTNAME);
  }

  /**Sets <code>value</code> as attribute value for FIRST_NAME using the alias name FirstName
   */
  public void setFirstName(String value) {
    setAttributeInternal(FIRSTNAME, value);
  }

  /**Gets the attribute value for LAST_NAME using the alias name LastName
   */
  public String getLastName() {
    return (String) getAttributeInternal(LASTNAME);
  }

  /**Sets <code>value</code> as attribute value for LAST_NAME using the alias name LastName
   */
  public void setLastName(String value) {
    setAttributeInternal(LASTNAME, value);
  }

  /**getAttrInvokeAccessor: generated method. Do not modify.
   */
  protected Object getAttrInvokeAccessor(int index, 
                                         AttributeDefImpl attrDef) throws Exception {
    switch (index) {
    case VALUE:
      return getValue();
    case LABEL:
      return getLabel();
    case FILTER:
      return getFilter();
    case FIRSTNAME:
      return getFirstName();
    case LASTNAME:
      return getLastName();
    default:
      return super.getAttrInvokeAccessor(index, attrDef);
    }
  }

  /**setAttrInvokeAccessor: generated method. Do not modify.
   */
  protected void setAttrInvokeAccessor(int index, Object value, 
                                       AttributeDefImpl attrDef) throws Exception {
    switch (index) {
    case VALUE:
      setValue((Number)value);
      return;
    case FILTER:
      setFilter((Number)value);
      return;
    case FIRSTNAME:
      setFirstName((String)value);
      return;
    case LASTNAME:
      setLastName((String)value);
      return;
    default:
      super.setAttrInvokeAccessor(index, value, attrDef);
      return;
    }
  }
}
