package demo.model.queries;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmployeesImpl extends ViewObjectImpl {
  /**This is the default constructor (do not remove)
   */
  public EmployeesImpl() {
  }
}
