/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package example.client;

import example.common.ExampleModule;

import oracle.jbo.client.remote.ApplicationModuleImpl;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ExampleModuleClient extends ApplicationModuleImpl implements ExampleModule {
  /**This is the default constructor (do not remove)
   */
  public ExampleModuleClient() {
  }
  public void collectDataUsingStoredProcedure(String v, Number n, Date d) {
    Object _ret = 
      this.riInvokeExportedMethod(this,"collectDataUsingStoredProcedure",new String [] {"java.lang.String","oracle.jbo.domain.Number","oracle.jbo.domain.Date"},new Object[] {v, n, d});
    return;
  }
}
