/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package test.hr;

import oracle.jbo.server.ViewRowSetImpl;
import oracle.jbo.Row;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class EmpViewImpl extends DeclarativeRecalculatingViewObjectImpl  {
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public EmpViewImpl() {
  }

  /**
   * 
   *  Sample exportable method.
   */
  public void sampleEmpViewImplExportable() {
  }

  /**
   * 
   *  Sample exportable method.
   */
  public void sampleEmpViewImplExportable2(String testParam1) {
  }
}
