/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package test.example.common;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---------------------------------------------------------------------

public interface WomenRow extends PeopleRow  {
  oracle.jbo.domain.Number getId();

  void setId(oracle.jbo.domain.Number value);

  String getSex();

  void setSex(String value);

  String getName();

  void setName(String value);

  String getWomanAttr();

  void setWomanAttr(String value);
}
