/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package xml2000demo.common;
import oracle.jbo.common.JboResourceBundle;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---------------------------------------------------------------------

public class EmpImplMsgBundle extends JboResourceBundle  {
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public EmpImplMsgBundle() {
  }

  /**
   * 
   * @return an array of key-value pairs.
   */
  public Object[][] getContents() {
    return super.getMergedArray(sMessageStrings, super.getContents());
  }

  static final Object[][] sMessageStrings = {
    {"Emp_Rule_0", "Salary more than $1000 times the length of the name"},
    {"Sal_Rule_0", "Salary below $100 is too low!"}};



}