/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.0.0, build 060119.1546.05277)

package remoteservices;

import javax.xml.rpc.*;

public interface DeptService_Service extends javax.xml.rpc.Service {
    public remoteservices.DeptService_PortType getDeptServiceSoapHttpPort() throws javax.xml.rpc.ServiceException;
}
