/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package test.model.common;
import oracle.jbo.ViewObject;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---------------------------------------------------------------------

public interface EmployeeList extends ViewObject  {
  void markEmployeeAsSelected(oracle.jbo.domain.Number empno);

  EmployeeListRow findEmployeeListRowByKey(oracle.jbo.domain.Number empno);


  void resetSelection();

  void markEmployeeAsSelectedUsingString(String empnoString);
}
