/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package test.model.common;
import oracle.jbo.Row;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---------------------------------------------------------------------

public interface EmployeeListRow extends Row  {
  oracle.jbo.domain.Number getEmpno();

  void setEmpno(oracle.jbo.domain.Number value);

  String getEname();

  void setEname(String value);

  Boolean getSelected();

  void setSelected(Boolean value);
}
