/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package demo.model.common;
import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface ExampleModule extends ApplicationModule {
  void clearFilterOnDeptView();
  void filterDeptViewByDname(String dname);
}
