/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package test.model;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LocationsImpl extends EntityImpl {
  public static final int LOCATIONID = 0;
  public static final int STREETADDRESS = 1;
  public static final int POSTALCODE = 2;
  public static final int CITY = 3;
  public static final int STATEPROVINCE = 4;
  public static final int COUNTRYID = 5;
  public static final int COUNTRIES = 6;
  private static EntityDefImpl mDefinitionObject;

  /**This is the default constructor (do not remove)
   */
  public LocationsImpl() {
  }

  /**Retrieves the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject() {
    if (mDefinitionObject == null) {
      mDefinitionObject = (EntityDefImpl)EntityDefImpl.findDefObject("test.model.Locations");
    }
    return mDefinitionObject;
  }

  /**Gets the attribute value for LocationId, using the alias name LocationId
   */
  public Number getLocationId() {
    return (Number)getAttributeInternal(LOCATIONID);
  }

  /**Sets <code>value</code> as the attribute value for LocationId
   */
  public void setLocationId(Number value) {
    setAttributeInternal(LOCATIONID, value);
  }

  /**Gets the attribute value for StreetAddress, using the alias name StreetAddress
   */
  public String getStreetAddress() {
    return (String)getAttributeInternal(STREETADDRESS);
  }

  /**Sets <code>value</code> as the attribute value for StreetAddress
   */
  public void setStreetAddress(String value) {
    setAttributeInternal(STREETADDRESS, value);
  }

  /**Gets the attribute value for PostalCode, using the alias name PostalCode
   */
  public String getPostalCode() {
    return (String)getAttributeInternal(POSTALCODE);
  }

  /**Sets <code>value</code> as the attribute value for PostalCode
   */
  public void setPostalCode(String value) {
    setAttributeInternal(POSTALCODE, value);
  }

  /**Gets the attribute value for City, using the alias name City
   */
  public String getCity() {
    return (String)getAttributeInternal(CITY);
  }

  /**Sets <code>value</code> as the attribute value for City
   */
  public void setCity(String value) {
    setAttributeInternal(CITY, value);
  }

  /**Gets the attribute value for StateProvince, using the alias name StateProvince
   */
  public String getStateProvince() {
    return (String)getAttributeInternal(STATEPROVINCE);
  }

  /**Sets <code>value</code> as the attribute value for StateProvince
   */
  public void setStateProvince(String value) {
    setAttributeInternal(STATEPROVINCE, value);
  }

  /**Gets the attribute value for CountryId, using the alias name CountryId
   */
  public String getCountryId() {
    return (String)getAttributeInternal(COUNTRYID);
  }

  /**Sets <code>value</code> as the attribute value for CountryId
   */
  public void setCountryId(String value) {
    setAttributeInternal(COUNTRYID, value);
  }

  /**getAttrInvokeAccessor: generated method. Do not modify.
   */
  protected Object getAttrInvokeAccessor(int index, 
                                         AttributeDefImpl attrDef) throws Exception {
    switch (index) {
    case LOCATIONID:
      return getLocationId();
    case STREETADDRESS:
      return getStreetAddress();
    case POSTALCODE:
      return getPostalCode();
    case CITY:
      return getCity();
    case STATEPROVINCE:
      return getStateProvince();
    case COUNTRYID:
      return getCountryId();
    case COUNTRIES:
      return getCountries();
    default:
      return super.getAttrInvokeAccessor(index, attrDef);
    }
  }

  /**setAttrInvokeAccessor: generated method. Do not modify.
   */
  protected void setAttrInvokeAccessor(int index, Object value, 
                                       AttributeDefImpl attrDef) throws Exception {
    switch (index) {
    case LOCATIONID:
      setLocationId((Number)value);
      return;
    case STREETADDRESS:
      setStreetAddress((String)value);
      return;
    case POSTALCODE:
      setPostalCode((String)value);
      return;
    case CITY:
      setCity((String)value);
      return;
    case STATEPROVINCE:
      setStateProvince((String)value);
      return;
    case COUNTRYID:
      setCountryId((String)value);
      return;
    default:
      super.setAttrInvokeAccessor(index, value, attrDef);
      return;
    }
  }

  /**Gets the associated entity CountriesImpl
   */
  public CountriesImpl getCountries() {
    return (CountriesImpl)getAttributeInternal(COUNTRIES);
  }

  /**Sets <code>value</code> as the associated entity CountriesImpl
   */
  public void setCountries(CountriesImpl value) {
    setAttributeInternal(COUNTRIES, value);
  }
  protected void create(AttributeList nameValuePair) {
    super.create(nameValuePair);
    setLocationId((new SequenceImpl("LOCATIONS_SEQ",getDBTransaction())).getSequenceNumber());
  }

  /**Creates a Key object based on given key constituents
   */
  public static Key createPrimaryKey(Number locationId) {
    return new Key(new Object[]{locationId});
  }
}
