/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package test.model;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LocationsViewRowImpl extends ViewRowImpl {
  public static final int LOCATIONID = 0;
  public static final int STREETADDRESS = 1;
  public static final int POSTALCODE = 2;
  public static final int CITY = 3;
  public static final int STATEPROVINCE = 4;
  public static final int COUNTRYID = 5;

  /**This is the default constructor (do not remove)
   */
  public LocationsViewRowImpl() {
  }

  /**Gets Locations entity object.
   */
  public LocationsImpl getLocations() {
    return (LocationsImpl)getEntity(0);
  }

  /**Gets the attribute value for LOCATION_ID using the alias name LocationId
   */
  public Number getLocationId() {
    return (Number) getAttributeInternal(LOCATIONID);
  }

  /**Sets <code>value</code> as attribute value for LOCATION_ID using the alias name LocationId
   */
  public void setLocationId(Number value) {
    setAttributeInternal(LOCATIONID, value);
  }

  /**Gets the attribute value for STREET_ADDRESS using the alias name StreetAddress
   */
  public String getStreetAddress() {
    return (String) getAttributeInternal(STREETADDRESS);
  }

  /**Sets <code>value</code> as attribute value for STREET_ADDRESS using the alias name StreetAddress
   */
  public void setStreetAddress(String value) {
    setAttributeInternal(STREETADDRESS, value);
  }

  /**Gets the attribute value for POSTAL_CODE using the alias name PostalCode
   */
  public String getPostalCode() {
    return (String) getAttributeInternal(POSTALCODE);
  }

  /**Sets <code>value</code> as attribute value for POSTAL_CODE using the alias name PostalCode
   */
  public void setPostalCode(String value) {
    setAttributeInternal(POSTALCODE, value);
  }

  /**Gets the attribute value for CITY using the alias name City
   */
  public String getCity() {
    return (String) getAttributeInternal(CITY);
  }

  /**Sets <code>value</code> as attribute value for CITY using the alias name City
   */
  public void setCity(String value) {
    setAttributeInternal(CITY, value);
  }

  /**Gets the attribute value for STATE_PROVINCE using the alias name StateProvince
   */
  public String getStateProvince() {
    return (String) getAttributeInternal(STATEPROVINCE);
  }

  /**Sets <code>value</code> as attribute value for STATE_PROVINCE using the alias name StateProvince
   */
  public void setStateProvince(String value) {
    setAttributeInternal(STATEPROVINCE, value);
  }

  /**Gets the attribute value for COUNTRY_ID using the alias name CountryId
   */
  public String getCountryId() {
    return (String) getAttributeInternal(COUNTRYID);
  }

  /**Sets <code>value</code> as attribute value for COUNTRY_ID using the alias name CountryId
   */
  public void setCountryId(String value) {
    setAttributeInternal(COUNTRYID, value);
  }

  /**getAttrInvokeAccessor: generated method. Do not modify.
   */
  protected Object getAttrInvokeAccessor(int index, 
                                         AttributeDefImpl attrDef) throws Exception {
    switch (index) {
    case LOCATIONID:
      return getLocationId();
    case STREETADDRESS:
      return getStreetAddress();
    case POSTALCODE:
      return getPostalCode();
    case CITY:
      return getCity();
    case STATEPROVINCE:
      return getStateProvince();
    case COUNTRYID:
      return getCountryId();
    default:
      return super.getAttrInvokeAccessor(index, attrDef);
    }
  }

  /**setAttrInvokeAccessor: generated method. Do not modify.
   */
  protected void setAttrInvokeAccessor(int index, Object value, 
                                       AttributeDefImpl attrDef) throws Exception {
    switch (index) {
    case LOCATIONID:
      setLocationId((Number)value);
      return;
    case STREETADDRESS:
      setStreetAddress((String)value);
      return;
    case POSTALCODE:
      setPostalCode((String)value);
      return;
    case CITY:
      setCity((String)value);
      return;
    case STATEPROVINCE:
      setStateProvince((String)value);
      return;
    case COUNTRYID:
      setCountryId((String)value);
      return;
    default:
      super.setAttrInvokeAccessor(index, value, attrDef);
      return;
    }
  }
}
