package test.client;

import oracle.jbo.client.remote.ViewUsageImpl;
import oracle.jbo.domain.Array;

import test.common.EmpViewWithNamedBindingStyle;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmpViewWithNamedBindingStyleClient extends ViewUsageImpl implements EmpViewWithNamedBindingStyle {
  /**This is the default constructor (do not remove)
   */
  public EmpViewWithNamedBindingStyleClient() {
  }
  public void setNamesToFind(String[] names) {
    Object _ret = 
      getApplicationModuleProxy().riInvokeExportedMethod(this,"setNamesToFind",new String [] {"[Ljava.lang.String;"},new Object[] {names});
    return;
  }
}
