package test.client;
import oracle.jbo.client.remote.ViewUsageImpl;

import test.common.EmpView;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmpViewClient extends ViewUsageImpl implements EmpView {
  /**This is the default constructor (do not remove)
   */
  public EmpViewClient() {
  }
  public void setNamesToFind(String[] names) {
    Object _ret = 
      getApplicationModuleProxy().riInvokeExportedMethod(this,"setNamesToFind",new String [] {"[Ljava.lang.String;"},new Object[] {names});
    return;
  }
}
