package demo.model.common;
import oracle.jbo.ApplicationModule;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface HRModule extends ApplicationModule {
  RowIterator lovEmpsForDepartmentReadOnly(Number departmentId);
  void refreshLovEmpsReadOnly();
  RowIterator lovEmpsForDepartment(Number departmentId);
  void refreshLovEmps();
}
