/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package test.model.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Mar 20 12:28:05 CET 2009
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    void addInformationMessageTest();
}
