/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package com.somecustomer.someapp;
import com.somecompany.someapp.ExpertViewObjectImpl;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class CustomizedViewImpl extends ExpertViewObjectImpl {
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public CustomizedViewImpl()
  {
  }
}
