/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package com.somecompany.someapp;
import oracle.jbo.server.ViewObjectImpl;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class ExpertViewObjectImpl extends ViewObjectImpl {
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public ExpertViewObjectImpl()
  {
  }
}
