/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package test.model;
import oracle.jbo.domain.Number;
import oracle.jbo.server.ApplicationModuleImpl;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---------------------------------------------------------------------

public class TestModuleImpl extends ApplicationModuleImpl implements test.model.common.TestModule  {
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public TestModuleImpl() {
  }

  public void prepareToShowEmployeeList() {
    getEmpView().setWhereClauseParams(new Object[]{new Number(1),new Number(2)});
  }

  /**
   * 
   *  Sample exportable method.
   */
  public void sampleTestModuleImplExportable() {
  }

  /**
   * 
   *  Sample exportable method.
   */
  public void sampleTestModuleImplExportable2(String testParam1) {
  }

  /**
   * 
   *  Sample main for debugging Business Components code using the tester.
   */
  public static void main(String[] args) {
    launchTester("test.model", "TestModuleLocal");
  }

  /**
   * 
   *  Container's getter for EmpView
   */
  public EmpViewImpl getEmpView() {
    return (EmpViewImpl)findViewObject("EmpView");
  }
}
