/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package test;

import java.sql.PreparedStatement;
import java.sql.SQLException;

import oracle.jbo.server.QueryCollection;
import oracle.jbo.server.TransactionEvent;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DeptViewImpl extends ViewObjectImpl {
    /**This is the default constructor (do not remove)
     */
    public DeptViewImpl() {
    }

    public void beforeRollback(TransactionEvent transactionEvent) {
        //  super.beforeRollback(transactionEvent);
    }

    public void afterRollback(TransactionEvent transactionEvent) {
        // super.afterRollback(transactionEvent);
    }

    protected void bindParametersForCollection(QueryCollection qc, 
                                               Object[] params, 
                                               PreparedStatement stmt) throws SQLException {
        super.bindParametersForCollection(qc, params, stmt);
        System.out.println("### Executed Query for View Object " + 
                           getFullName());
    }
}
