/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package test;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DeptViewImpl extends CustomViewObjectImpl {
  /**This is the default constructor (do not remove)
   */
  public DeptViewImpl() {
  }
}
