/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package demo.model;
import oracle.jbo.server.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HRModuleImpl extends ApplicationModuleImpl {
  /**This is the default constructor (do not remove)
   */
  public HRModuleImpl() {
  }

  /**Container's getter for EmpView1
   */
  public EmpViewImpl getEmpView1() {
    return (EmpViewImpl)findViewObject("EmpView1");
  }

  /**Sample main for debugging Business Components code using the tester.
   */
  public static void main(String[] args) {
    launchTester("demo.model", /* package name */
      "HRModuleLocal" /* Configuration Name */);
  }
}
