/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package oracle.demo.model.queries;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jul 11 14:28:57 BST 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AllObjectsResultsQueryImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AllObjectsResultsQueryImpl() {
    }

    /**
     * Returns the variable value for searchTerm.
     * @return variable value for searchTerm
     */
    public String getsearchTerm() {
        return (String)ensureVariableManager().getVariableValue("searchTerm");
    }

    /**
     * Sets <code>value</code> for variable searchTerm.
     * @param value value to bind as searchTerm
     */
    public void setsearchTerm(String value) {
        ensureVariableManager().setVariableValue("searchTerm", value);
    }
}
