/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package oracle.demo.model.client;

import java.util.List;

import oracle.demo.model.common.AutoReduceAM;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jul 11 14:46:12 BST 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AutoReduceAMClient extends ApplicationModuleImpl implements AutoReduceAM {
    /**
     * This is the default constructor (do not remove).
     */
    public AutoReduceAMClient() {
    }

    public List<String> autoSuggestCandidates(String searchTerm,
                                              int returnCount) {
        Object _ret =
            this.riInvokeExportedMethod(this,"autoSuggestCandidates",new String [] {"java.lang.String","int"},new Object[] {searchTerm, new Integer(returnCount)});
        return (List<String>)_ret;
    }
}
