/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package extendsproject.common;

import oracle.jbo.common.JboResourceBundle;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public class DeptExImplMsgBundle extends JboResourceBundle {
    static final Object[][] sMessageStrings = {
{ "Loc_Rule_0", "Location Cannot be X !" }};

    /**This is the default constructor (do not remove)
     */
    public DeptExImplMsgBundle() {
    }

    /**@return an array of key-value pairs.
     */
    public Object[][] getContents() {
        return super.getMergedArray(sMessageStrings, super.getContents());
    }
}
