/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package model;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.RowSet;
import oracle.jbo.Session;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class AppModuleImpl extends ApplicationModuleImpl 
{
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public AppModuleImpl()
  {
  }

  /**
   * 
   *  Container's getter for EmployeesView1
   */
  public EmployeesViewImpl getEmployeesView1()
  {
    return (EmployeesViewImpl)findViewObject("EmployeesView1");
  }



  /**
   * 
   *  Sample exportable method.
   */
  public void sampleAppModuleImplExportable()
  {
  }

  /**
   * 
   *  Sample exportable method.
   */
  public void sampleAppModuleImplExportable2(String testParam1)
  {
  }

  /**
   * 
   *  Sample main for debugging Business Components code using the tester.
   */
  public static void main(String[] args)
  {
    launchTester("model", "AppModuleLocal");
  }

  protected void prepareSession(Session session)
  {
    super.prepareSession(session);
    this.getEmployeesView1().setAccessMode(RowSet.RANGE_PAGING_AUTO_POST);
  }
}
