/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package test.model.client;

import oracle.jbo.client.remote.ApplicationModuleImpl;

import test.model.common.ExampleModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Dec 16 12:52:03 CET 2009
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ExampleModuleClient extends ApplicationModuleImpl implements ExampleModule {
    /**
     * This is the default constructor (do not remove).
     */
    public ExampleModuleClient() {
    }

    public void setSessionFavoriteColor(String color) {
        Object _ret =
            this.riInvokeExportedMethod(this,"setSessionFavoriteColor",new String [] {"java.lang.String"},new Object[] {color});
        return;
    }
}
