/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package test.model.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Nov 03 20:00:37 CET 2009
// ---------------------------------------------------------------------
public interface MailService extends ApplicationModule {
    void createNewMailAndPrimaryRecipient();
}
