/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package test.model;
import oracle.jbo.server.ViewRowImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---------------------------------------------------------------------

public class EmployeeListRowImpl extends ViewRowImpl implements test.model.common.EmployeeListRow  {


  public static final int EMPNO = 0;
  public static final int ENAME = 1;
  public static final int SELECTED = 2;
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public EmployeeListRowImpl() {
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Empno
   */
  public Number getEmpno() {
    return (Number)getAttributeInternal(EMPNO);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Empno
   */
  public void setEmpno(Number value) {
    setAttributeInternal(EMPNO, value);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Ename
   */
  public String getEname() {
    return (String)getAttributeInternal(ENAME);
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Ename
   */
  public void setEname(String value) {
    setAttributeInternal(ENAME, value);
  }

  /**
   * 
   *  Gets the attribute value for the calculated attribute Selected
   */
  public Boolean getSelected() {
    /*
     * NOTE: Here we return Boolean.FALSE if the flag is null
     *       since the 
     */
    return (Boolean)getAttributeInternal(SELECTED);
//    Boolean val = (Boolean)getAttributeInternal(SELECTED);
//    return val != null ? val : Boolean.FALSE;
  }

  /**
   * 
   *  Sets <code>value</code> as the attribute value for the calculated attribute Selected
   */
  public void setSelected(Boolean value) {
    setAttributeInternal(SELECTED, value);
  }
  //  Generated method. Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
    switch (index)
      {
      case EMPNO:
        return getEmpno();
      case ENAME:
        return getEname();
      case SELECTED:
        return getSelected();
      default:
        return super.getAttrInvokeAccessor(index, attrDef);
      }
  }
  //  Generated method. Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
    switch (index)
      {
      case EMPNO:
        setEmpno((Number)value);
        return;
      case ENAME:
        setEname((String)value);
        return;
      case SELECTED:
        setSelected((Boolean)value);
        return;
      default:
        super.setAttrInvokeAccessor(index, value, attrDef);
        return;
      }
  }
}
