/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package test.model.client;

import java.util.Set;

import oracle.jbo.client.remote.ApplicationModuleImpl;

import test.model.common.AppModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed May 07 17:57:52 CEST 2008
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleClient extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleClient() {
    }
    public void processSelectedEmployees(Set s) {
        Object _ret =
            this.riInvokeExportedMethod(this,"processSelectedEmployees",new String [] {"java.util.Set"},new Object[] {s});
        return;
    }
    public void processSelectedDepartments(Set s) {
        Object _ret =
            this.riInvokeExportedMethod(this,"processSelectedDepartments",new String [] {"java.util.Set"},new Object[] {s});
        return;
    }
}
