/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package example;

import example.common.ExampleModule;

import java.sql.PreparedStatement;

import java.sql.SQLException;

import java.util.StringTokenizer;

import oracle.jbo.JboException;
import oracle.jbo.client.Configuration;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ExampleModuleImpl extends ApplicationModuleImpl implements ExampleModule {
  /**This is the default constructor (do not remove)
   */
  public ExampleModuleImpl() {
  }

  /**Sample main for debugging Business Components code using the tester.
   */
  public static void main(String[] args) {
    launchTester("example", /* package name */
      "ExampleModuleLocal" /* Configuration Name */);
  }

  private void callStoredProcedure(String stmt, Object[] bindVars) {
    PreparedStatement st = null;
    try {
      // 1. Create a JDBC PreparedStatement for 
      st = getDBTransaction().createPreparedStatement("begin "+stmt+";end;",0);
      if (bindVars != null) {
        // 2. Loop over values for the bind variables passed in, if any
        for (int z = 0; z < bindVars.length; z++) {
          // 3. Set the value of each bind variable in the statement
          st.setObject(z + 1, bindVars[z]);
        }
      }
      // 4. Execute the statement
      st.executeUpdate();
    }
    catch (SQLException e) {
      throw new JboException(e);
    }
    finally {
      if (st != null) {
        try {
          // 5. Close the statement
          st.close();
        }
        catch (SQLException e) {}
      }
    }
  }
  
 
  public void collectDataUsingStoredProcedure(String v, Number n, Date d) {
    Object[] procArgs = new Object[]{v,n,d};
    callStoredProcedure("example_pkg.do_something(?,?,?)",procArgs);
    getDBTransaction().commit();
    /*
     * Force the query displaying the data in the example table to re-execute
     */
    getExamplePkgTable().executeQuery();
  }

  /**Container's getter for ExamplePkgTable
   */
  public ExamplePkgTableImpl getExamplePkgTable() {
    return (ExamplePkgTableImpl)findViewObject("ExamplePkgTable");
  }
}
