/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package test;
import oracle.jbo.RowIterator;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.JboEventListener;
import oracle.jbo.server.JboEventObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmpDefImpl extends EntityDefImpl {
  private static boolean wiredup = false;

  /**This is the default constructor (do not remove)
   */
  public EmpDefImpl() {
  }
  public static void linkEvents() {
    if (!wiredup) {
      ((EmpDefImpl)EmpImpl.getDefinitionObject()).linkDeptOnDnameOrLocChanged();
      wiredup = true;
    }
  }

  /**links this object as a subscriber for the event OnDnameOrLocChanged
   */
  public void linkDeptOnDnameOrLocChanged() {
    DeptDefImpl pub = (DeptDefImpl)test.DeptImpl.getDefinitionObject();
    pub.addOnDnameOrLocChangedListener(new Emp_DeptOnDnameOrLocChangedAdapter(this));
  }

  /**unlinks this object as a subscriber for the event OnDnameOrLocChanged
   */
  public void unlinkDeptOnDnameOrLocChanged() {
    DeptDefImpl pub = (DeptDefImpl)test.DeptImpl.getDefinitionObject();
    pub.removeOnDnameOrLocChangedListener(new Emp_DeptOnDnameOrLocChangedAdapter(this));
  }
}
class Emp_DeptOnDnameOrLocChangedAdapter implements JboEventListener {
  EmpDefImpl mAdaptee;

  /**Constructs the adapter for an event
   */
  Emp_DeptOnDnameOrLocChangedAdapter(EmpDefImpl adaptee) {
    this.mAdaptee = adaptee;
  }

  /**Listens for the event OnDnameOrLocChanged
   */
  public void JboEvent(JboEventObject e) {
    try {
      EmpImpl instance;
      RowIterator iter;
      iter = ((DeptImpl)e.getSource()).getEmp();
      while (iter.hasNext()) {
        instance = (EmpImpl)iter.next();
        instance.DeptOnDnameOrLocChanged_Handler(e);
      }
    } catch (Exception ex) {
      ex.printStackTrace();
    }
  }

  /**Compares the two objects for same adaptee
   */
  public boolean equals(Object other) {
    return (other instanceof Emp_DeptOnDnameOrLocChangedAdapter) ? ((Emp_DeptOnDnameOrLocChangedAdapter)other).mAdaptee.equals(mAdaptee) : false;
  }
}
