/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package model;

import java.util.Locale;


import oracle.jbo.server.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl {
    /**This is the default constructor (do not remove)
     */
    public AppModuleImpl() {
    }

    /**Sample main for debugging Business Components code using the tester.
     */
    public static void main(String[] args) {
        launchTester("model", /* package name */
      "AppModuleLocal" /* Configuration Name */);
    }

    /**Container's getter for DeptView
     */
    public DeptViewImpl getDeptView() {
        return (DeptViewImpl)findViewObject("DeptView");
    }

  /**Container's getter for DepartmentList
   */
  public DeptViewImpl getDepartmentList() {
    return (DeptViewImpl)findViewObject("DepartmentList");
  }
}
