/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package example.model.common;

import oracle.jbo.common.JboResourceBundle;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public class EmpImplMsgBundle extends JboResourceBundle {
    static final Object[][] sMessageStrings = 
    {
    { "Ssn_FMT_FORMAT", "" },
    { "Ssn_FMT_FORMATTER", "example.fwkext.SocialSecurityNumberFormatter" }};

    /**This is the default constructor (do not remove)
     */
    public EmpImplMsgBundle() {
    }

    /**@return an array of key-value pairs.
     */
    public Object[][] getContents() {
        return super.getMergedArray(sMessageStrings, super.getContents());
    }
}
