/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package test.model.services;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import test.model.queries.ProductExpertiseAreasImpl;
import test.model.queries.StaffImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SRServiceImpl extends ApplicationModuleImpl {
  /**This is the default constructor (do not remove)
   */
  public SRServiceImpl() {
  }

  /**Sample main for debugging Business Components code using the tester.
   */
  public static void main(String[] args) {
    launchTester("test.model.services", /* package name */
      "SRServiceLocal" /* Configuration Name */);
  }

  /**Container's getter for StaffList
   */
  public StaffImpl getStaffList() {
    return (StaffImpl)findViewObject("StaffList");
  }

  /**Container's getter for StaffExpertiseAreas
   */
  public ProductExpertiseAreasImpl getStaffExpertiseAreas() {
    return (ProductExpertiseAreasImpl)findViewObject("StaffExpertiseAreas");
  }

  /**Container's getter for ProductExpertiseForUser1
   */
  public ViewLinkImpl getProductExpertiseForUser1() {
    return (ViewLinkImpl)findViewLink("ProductExpertiseForUser1");
  }
}
