/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
// $Header: /cvs/ADFToyStoreJSF/ToyStoreModel/src/toystore/model/services/common/ToyStoreService.java,v 1.1.1.1 2006/01/26 21:47:22 steve Exp $
package toystore.model.services.common;
import oracle.jbo.ApplicationModule;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------
/**
 *
 * Generated interface. Do not modify.
 */
public interface ToyStoreService extends ApplicationModule {
  boolean validSignon(String username, String password);
  long currentQuantityInCart(String itemid);

  Double getCartTotal();
  boolean prepareToEditAccountInfoFor(String username);
  void prepareToCreateNewAccount();
  void createNewOrder(String currentUsername);

  String finalizeOrder();

  void addItemToCart(String itemid);
  void removeItemFromCart(String itemid);
  boolean adjustQuantityInCart(String[] itemid, long[] qty);
  boolean isCartEmpty();
  void removeShoppingCartItemsWithZeroQuantity();
}
