/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package test.model.client;
import oracle.jbo.client.remote.ApplicationModuleImpl;

import test.model.common.HRModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HRModuleClient extends ApplicationModuleImpl implements HRModule {
  /**This is the default constructor (do not remove)
   */
  public HRModuleClient() {
  }
  public void cancelChangesToCurrentEmployeeRow() {
    Object _ret = 
      this.riInvokeExportedMethod(this,"cancelChangesToCurrentEmployeeRow",null,null);
    return;
  }
}
