/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package test.model.client;
import oracle.jbo.client.remote.ApplicationModuleImpl;

import test.model.common.AppModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleClient extends ApplicationModuleImpl implements AppModule {
  /**This is the default constructor (do not remove)
   */
  public AppModuleClient() {
  }
  public void syncRegionListToCurrentLocationsCountry() {
    Object _ret = 
      this.riInvokeExportedMethod(this,"syncRegionListToCurrentLocationsCountry",null,null);
    return;
  }
}
