/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package test.model.client;

import oracle.jbo.client.remote.ViewUsageImpl;

import test.model.common.CitiesView;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CitiesViewClient extends ViewUsageImpl implements CitiesView {
  /**This is the default constructor (do not remove)
   */
  public CitiesViewClient() {
  }
  public void setCurrentCountryIdToNull() {
    Object _ret = 
      getApplicationModuleProxy().riInvokeExportedMethod(this,"setCurrentCountryIdToNull",null,null);
    return;
  }
}
