/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package test.model.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Nov 24 12:41:36 CET 2011
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    void performAppModuleLevelWork(Integer deptno, String locValue);
}
