/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package system.meta;
import oracle.jbo.server.ApplicationModuleImpl;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---    Warning: Do not modify method signatures of generated methods.
//  ---------------------------------------------------------------------

public class MetadataModuleImpl extends ApplicationModuleImpl  {
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public MetadataModuleImpl() {
  }


  /**
   * 
   *  Sample main for debugging Business Components code using the tester.
   */
  public static void main(String[] args) {
    launchTester("system.meta", "MetadataModuleLocal");
  }

  /**
   * 
   *  Container's getter for CurrentDBDate
   */
  public MetaObjectQueryImpl getCurrentDBDate() {
    return (MetaObjectQueryImpl)findViewObject("CurrentDBDate");
  }
}
