/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package test.model.client;
import oracle.jbo.client.remote.ApplicationModuleImpl;
//  ---------------------------------------------------------------------
//  ---    File generated by Oracle ADF Business Components Design Time.
//  ---    Custom code may be added to this class.
//  ---------------------------------------------------------------------

public class TestModuleClient extends ApplicationModuleImpl implements test.model.common.TestModule  {
  /**
   * 
   *  This is the default constructor (do not remove)
   */
  public TestModuleClient() {
  }

    public void testNewEmpAndNewDeptProgrammatically() {
        Object _ret = 
            this.riInvokeExportedMethod(this,"testNewEmpAndNewDeptProgrammatically",null,null);
        return;
    }
}
