/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package test.hr.common;
import oracle.jbo.common.JboResourceBundle;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class EmpViewRowImplMsgBundle extends JboResourceBundle 
{
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public EmpViewRowImplMsgBundle()
  {
  }

  /**
   * 
   * @return an array of key-value pairs.
   */
  public Object[][] getContents()
  {
    return super.getMergedArray(sMessageStrings, super.getContents());
  }

  static final Object[][] sMessageStrings = {
    {"SalaryPercentageOfManager_TOOLTIP", "Percentage of manager's salary"},
    {"ManagersSalary_LABEL", "Manager's Salary"},
    {"SalaryPercentageOfManager_LABEL", "Pct of Mgr"},
    {"WorksInDeptno_TOOLTIP", "The department this employee works in"},
    {"SalaryPercentageOfManager_FMT_FORMATTER", "oracle.jbo.format.DefaultNumberFormatter"},
    {"SalaryPercentageOfManager_FMT_FORMAT", "0.00%"},
    {"Mgr_LABEL", "Manager"},
    {"ManagersSalary_TOOLTIP", "The monthly pay of this employee's manager"},
    {"WorksInDeptno_LABEL", "Department"}};
}
