/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package test.model;

import java.sql.PreparedStatement;
import java.sql.SQLException;

import oracle.jbo.server.QueryCollection;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DeptViewImpl extends ViewObjectImpl {
  /**This is the default constructor (do not remove)
   */
  public DeptViewImpl() {
  }
  protected void bindParametersForCollection(QueryCollection qc, 
                                             Object[] params, 
                                             PreparedStatement stmt) throws SQLException {
    if (qc == null) {
      System.out.println("### Executed estimatedRowCount query for view object instance '"+getName()+"' ###");
    }
    else {
      System.out.println("### Executed query for view object instance '"+getName()+"' ###");
    }
    super.bindParametersForCollection(qc, params, stmt);
  }
}
