/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package test.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Oct 06 15:03:08 CEST 2008
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    void testReadOnlyScoredEmployees();

    void testEntityBasedScoredEmployees();
}
