/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package test.model.common;

import java.util.Set;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed May 07 17:57:52 CEST 2008
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    void processSelectedEmployees(Set s);
    void processSelectedDepartments(Set s);
}
