/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package test;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;


// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DemoModuleImpl extends ApplicationModuleImpl {
  /**This is the default constructor (do not remove)
   */
  public DemoModuleImpl() {
  }

  /**Sample main for debugging Business Components code using the tester.
   */
  public static void main(String[] args) {
    launchTester("test", /* package name */
      "DemoModuleLocal" /* Configuration Name */);
  }

  /**Container's getter for Employees
   */
  public ViewObjectImpl getEmployees() {
    return (ViewObjectImpl)findViewObject("Employees");
  }

  /**Container's getter for Regions
   */
  public ViewObjectImpl getRegions() {
    return (ViewObjectImpl)findViewObject("Regions");
  }

  /**Container's getter for Countries
   */
  public ViewObjectImpl getCountries() {
    return (ViewObjectImpl)findViewObject("Countries");
  }

  /**Container's getter for Locations
   */
  public ViewObjectImpl getLocations() {
    return (ViewObjectImpl)findViewObject("Locations");
  }

  /**Container's getter for Departments
   */
  public ViewObjectImpl getDepartments() {
    return (ViewObjectImpl)findViewObject("Departments");
  }

  /**Container's getter for CountriesInRegion
   */
  public ViewLinkImpl getCountriesInRegion() {
    return (ViewLinkImpl)findViewLink("CountriesInRegion");
  }

  /**Container's getter for LocationsForCountry
   */
  public ViewLinkImpl getLocationsForCountry() {
    return (ViewLinkImpl)findViewLink("LocationsForCountry");
  }

  /**Container's getter for DepartmentsAtLocation
   */
  public ViewLinkImpl getDepartmentsAtLocation() {
    return (ViewLinkImpl)findViewLink("DepartmentsAtLocation");
  }

  /**Container's getter for AllDepartments
   */
  public ViewObjectImpl getAllDepartments() {
    return (ViewObjectImpl)findViewObject("AllDepartments");
  }
}
