/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package paramform.model.queries;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ParameterFormItemsImpl extends ViewObjectImpl {
  /**This is the default constructor (do not remove)
   */
  public ParameterFormItemsImpl() {
  }

  /**Gets the bind variable value for TheFormId
   */
  public String getTheFormId() {
    return (String)getNamedWhereClauseParam("TheFormId");
  }

  /**Sets <code>value</code> for bind variable TheFormId
   */
  public void setTheFormId(String value) {
    setNamedWhereClauseParam("TheFormId", value);
  }
}
