/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package oracle.adfinsider.localdb.server.serviceinterface;

import java.lang.reflect.Method;

import java.util.List;

import javax.ejb.Remote;
import javax.ejb.Stateless;

import javax.interceptor.Interceptors;

import oracle.adfinsider.localdb.common.serviceinterface.HRModuleService;
import oracle.adfinsider.localdb.hrservices.common.CountriesViewSDO;

import oracle.jbo.common.Diagnostic;
import oracle.jbo.common.sdo.SDOHelper;
import oracle.jbo.common.service.types.FindControl;
import oracle.jbo.common.service.types.FindCriteria;
import oracle.jbo.server.svc.ServiceContextInterceptor;
import oracle.jbo.server.svc.ServiceImpl;
import oracle.jbo.service.errors.ServiceException;

import oracle.webservices.annotations.PortableWebService;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu May 09 10:03:01 EDT 2013
// ---------------------------------------------------------------------
@Stateless(name="oracle.adfinsider.localdb.common.HRModuleServiceBean", mappedName="HRModuleServiceBean")
@Remote(HRModuleService.class)
@PortableWebService(targetNamespace="/oracle/adfinsider/localdb/", serviceName="HRModuleService", portName="HRModuleServiceSoapHttpPort",
    endpointInterface="oracle.adfinsider.localdb.common.serviceinterface.HRModuleService")
@Interceptors( { ServiceContextInterceptor.class })
public class HRModuleServiceImpl extends ServiceImpl implements HRModuleService {
    private static boolean _isInited = false;

    /**
     * This is the default constructor (do not remove).
     */
    public HRModuleServiceImpl() {
        init();
        setApplicationModuleDefName("oracle.adfinsider.localdb.HRModule");
        setConfigurationName("HRModuleService");
    }

    /**
     * Generated method. Do not modify. Do initialization in the constructor
     */
    protected void init() {
        if (_isInited) {
            return;
        }
        synchronized (HRModuleServiceImpl.class) {
            if (_isInited) {
                return;
            }
            try {
                SDOHelper.INSTANCE.defineSchema("oracle/adfinsider/localdb/common/serviceinterface/", "HRModuleService.xsd");
                _isInited = true;
            } catch (Exception ex) {
                Diagnostic.printStackTrace(ex);
            }
        }
    }

    /**
     * getCountry: generated method. Do not modify.
     */
    public CountriesViewSDO getCountry(String countryId) throws ServiceException {
        return (CountriesViewSDO)get(new Object[] { countryId }, "CountriesView", CountriesViewSDO.class);
    }

    /**
     * findCountry: generated method. Do not modify.
     */
    public List<CountriesViewSDO> findCountry(FindCriteria findCriteria,
                                              FindControl findControl) throws ServiceException {
        return (List<CountriesViewSDO>)find(findCriteria, findControl, "CountriesView", CountriesViewSDO.class);
    }
}
