/* Copyright 2010, 2017, Oracle and/or its affiliates. All rights reserved. */
package demo.model.common;
import oracle.jbo.common.JboResourceBundle;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public class EmpViewRowImplMsgBundle extends JboResourceBundle {
  static final Object[][] sMessageStrings = 
  {
{ "HighSal_LABEL", "Salary Less Than" },
{ "EmpName_LABEL", "Employee Name" },
{ "LowSal_LABEL", "Salary Greater Than" }};

  /**This is the default constructor (do not remove)
   */
  public EmpViewRowImplMsgBundle() {
  }

  /**@return an array of key-value pairs.
   */
  public Object[][] getContents() {
    return super.getMergedArray(sMessageStrings, super.getContents());
  }
}
